const Map<String, String> ko = {
  'login': '로그인',
  'create_account': '계정 만들기',
  'already_have_account': '이미 계정이 있으신가요? 로그인',
  'name': '이름',
  'email': '이메일',
  'password': '비밀번호',
  'birth_date': '생년월일 (YYYY-MM-DD)',
  'phone': '전화번호',
  'enter_name': '이름을 입력하세요',
  'enter_email': '이메일을 입력하세요',
  'invalid_email': '유효하지 않은 이메일 주소입니다',
  'enter_password': '비밀번호를 입력하세요',
  'password_too_short': '비밀번호는 최소 6자 이상이어야 합니다',
  'enter_birth_date': '생년월일을 입력하세요',
  'invalid_date': '유효하지 않은 날짜 형식입니다',
  'enter_phone': '전화번호를 입력하세요',
  'age_restriction': '최소 18세 이상이어야 합니다',
  'auth_error': '인증 오류',
  'account_created': '계정이 성공적으로 생성되었습니다',
  'chats': '채팅',
  'hub': '허브',
  'converter': '변환기',
  'news': '뉴스',
  'profile': '프로필',
  'export_data': '사용자 데이터 내보내기',
  'send_data': '데이터 전송',
  'data_sent': '데이터가 성공적으로 전송되었습니다',
  'error_sending_data': '데이터 전송 오류',
  'type_message': '메시지를 입력하세요...',
  'no_messages': '아직 메시지가 없습니다.\n첫 번째로 보내세요!',
  'error_loading_messages': '메시지 로드 오류',
  'hello': '안녕하세요',
  'portfolio': '포트폴리오',
  'quick_actions': '빠른 작업',
  'send': '보내기',
  'receive': '받기',
  'deposit': '입금',
  'convert': '변환',
  'watchlist': '관심 목록',
  'no_watchlists': '아직 관심 목록이 없습니다',
  'recent_alerts': '최근 알림',
  'no_alerts': '아직 알림이 없습니다',
  'activities': '활동',
  'transactions': '거래',
  'orders': '주문',
  'alerts': '알림',
  'reports': '보고서',
  'no_transactions': '아직 거래가 없습니다',
  'no_orders': '아직 주문이 없습니다',
  'generate_report': '보고서 생성',
  'feed': '피드',
  'create_post': '게시물 작성',
  'write_post': '게시물을 작성하세요...',
  'post': '게시',
  'marketplace': '마켓플레이스',
  'bio': '소개',
  'update_bio': '소개 업데이트',
  'statistics': '통계',
  'points': '포인트',
  'followers': '팔로워',
  'settings': '설정',
  'themes': '테마',
  'languages': '언어',
  'integrations': '통합',
  'security': '보안',
  'logout': '로그아웃',
  'charts': '차트',
  'screener': '스크리너',
  'calculators': '계산기',
  'journal': '저널',
  'strategies': '전략',
  'backtesting': '백테스팅',
  'paper_trading': '모의 거래',
  'reminders': '알림',
  'researcher': '연구자',
  'dictionary': '사전',
  'heatmaps': '히트맵',
  'correlation': '상관관계',
  'football': '축구',
  'entertainment': '엔터테인먼트',
  'learning': '학습',
  'webinars': '웨비나',
  'add_indicator': '지표 추가',
  'filters': '필터',
  'run_screener': '스크리너 실행',
  'results': '결과',
  'position': '포지션',
  'fibonacci': '피보나치',
  'pivot_points': '피봇 포인트',
  'risk_percentage': '위험 비율',
  'stop_loss': '손절매',
  'calculate': '계산',
  'new_entry': '새 항목',
  'add_entry': '항목 추가',
  'select_strategy': '전략 선택',
  'asset': '자산',
  'start_date': '시작 날짜',
  'end_date': '종료 날짜',
  'run_backtest': '백테스트 실행',
  'backtest_results': '백테스트 결과',
  'balance': '잔액',
  'positions': '포지션',
  'place_order': '주문하기',
  'buy': '매수',
  'sell': '매도',
  'quantity': '수량',
  'price': '가격',
  'title': '제목',
  'date': '날짜',
  'add_reminder': '알림 추가',
  'search_query': '검색 쿼리',
  'search': '검색',
  'search_term': '검색어',
  'amount': '금액',
  'result': '결과',
  'select_assets': '자산 선택',
  'calculate_correlation': '상관관계 계산',
  'trading_simulator': '트레이딩 시뮬레이터',
  'score': '점수',
  'start_game': '게임 시작',
  'quiz': '퀴즈',
  'quiz_complete': '퀴즈 완료',
  'movies': '영화',
  'menu': '메뉴',
  'error_loading': '데이터 로드 오류',
  'close': '닫기',
};