const Map<String, String> ru = {
  'login': 'Войти',
  'create_account': 'Создать аккаунт',
  'already_have_account': 'Уже есть аккаунт? Войти',
  'name': 'Имя',
  'email': 'Электронная почта',
  'password': 'Пароль',
  'birth_date': 'Дата рождения (ГГГГ-ММ-ДД)',
  'phone': 'Номер телефона',
  'enter_name': 'Пожалуйста, введите ваше имя',
  'enter_email': 'Пожалуйста, введите вашу электронную почту',
  'invalid_email': 'Недействительный адрес электронной почты',
  'enter_password': 'Пожалуйста, введите ваш пароль',
  'password_too_short': 'Пароль должен содержать не менее 6 символов',
  'enter_birth_date': 'Пожалуйста, введите вашу дату рождения',
  'invalid_date': 'Неверный формат даты',
  'enter_phone': 'Пожалуйста, введите ваш номер телефона',
  'age_restriction': 'Вам должно быть не менее 18 лет',
  'auth_error': 'Ошибка аутентификации',
  'account_created': 'Аккаунт успешно создан',
  'chats': 'Чаты',
  'hub': 'Хаб',
  'converter': 'Конвертер',
  'news': 'Новости',
  'profile': 'Профиль',
  'export_data': 'Экспорт данных пользователя',
  'send_data': 'Отправить данные',
  'data_sent': 'Данные успешно отправлены',
  'error_sending_data': 'Ошибка отправки данных',
  'type_message': 'Введите ваше сообщение...',
  'no_messages': 'Пока нет сообщений.\nБудьте первым!',
  'error_loading_messages': 'Ошибка загрузки сообщений',
  'hello': 'Привет',
  'portfolio': 'Портфель',
  'quick_actions': 'Быстрые действия',
  'send': 'Отправить',
  'receive': 'Получить',
  'deposit': 'Депозит',
  'convert': 'Конвертировать',
  'watchlist': 'Список наблюдения',
  'no_watchlists': 'Пока нет списков наблюдения',
  'recent_alerts': 'Недавние оповещения',
  'no_alerts': 'Пока нет оповещений',
  'activities': 'Активность',
  'transactions': 'Транзакции',
  'orders': 'Ордера',
  'alerts': 'Оповещения',
  'reports': 'Отчеты',
  'no_transactions': 'Пока нет транзакций',
  'no_orders': 'Пока нет ордеров',
  'generate_report': 'Создать отчет',
  'feed': 'Лента',
  'create_post': 'Создать публикацию',
  'write_post': 'Напишите вашу публикацию...',
  'post': 'Опубликовать',
  'marketplace': 'Маркетплейс',
  'bio': 'Биография',
  'update_bio': 'Обновить биографию',
  'statistics': 'Статистика',
  'points': 'Баллы',
  'followers': 'Подписчики',
  'settings': 'Настройки',
  'themes': 'Темы',
  'languages': 'Языки',
  'integrations': 'Интеграции',
  'security': 'Безопасность',
  'logout': 'Выйти',
  'charts': 'Графики',
  'screener': 'Скринер',
  'calculators': 'Калькуляторы',
  'journal': 'Журнал',
  'strategies': 'Стратегии',
  'backtesting': 'Бэктестинг',
  'paper_trading': 'Бумажная торговля',
  'reminders': 'Напоминания',
  'researcher': 'Исследователь',
  'dictionary': 'Словарь',
  'heatmaps': 'Тепловые карты',
  'correlation': 'Корреляция',
  'football': 'Футбол',
  'entertainment': 'Развлечения',
  'learning': 'Обучение',
  'webinars': 'Вебинары',
  'add_indicator': 'Добавить индикатор',
  'filters': 'Фильтры',
  'run_screener': 'Запустить скринер',
  'results': 'Результаты',
  'position': 'Позиция',
  'fibonacci': 'Фибоначчи',
  'pivot_points': 'Пивот-поинты',
  'risk_percentage': 'Процент риска',
  'stop_loss': 'Стоп-лосс',
  'calculate': 'Рассчитать',
  'new_entry': 'Новая запись',
  'add_entry': 'Добавить запись',
  'select_strategy': 'Выбрать стратегию',
  'asset': 'Актив',
  'start_date': 'Дата начала',
  'end_date': 'Дата окончания',
  'run_backtest': 'Запустить бэктест',
  'backtest_results': 'Результаты бэктеста',
  'balance': 'Баланс',
  'positions': 'Позиции',
  'place_order': 'Разместить ордер',
  'buy': 'Купить',
  'sell': 'Продать',
  'quantity': 'Количество',
  'price': 'Цена',
  'title': 'Название',
  'date': 'Дата',
  'add_reminder': 'Добавить напоминание',
  'search_query': 'Поисковый запрос',
  'search': 'Поиск',
  'search_term': 'Поисковый термин',
  'amount': 'Сумма',
  'result': 'Результат',
  'select_assets': 'Выбрать активы',
  'calculate_correlation': 'Рассчитать корреляцию',
  'trading_simulator': 'Торговый симулятор',
  'score': 'Счет',
  'start_game': 'Начать игру',
  'quiz': 'Викторина',
  'quiz_complete': 'Викторина завершена',
  'movies': 'Фильмы',
  'menu': 'Меню',
  'error_loading': 'Ошибка загрузки данных',
  'close': 'Закрыть',
};