const Map<String, String> it = {
  'login': 'Accedi',
  'create_account': 'Crea account',
  'already_have_account': 'Hai già un account? Accedi',
  'name': 'Nome',
  'email': 'Email',
  'password': 'Password',
  'birth_date': 'Data di nascita (AAAA-MM-GG)',
  'phone': 'Numero di telefono',
  'enter_name': 'Inserisci il tuo nome',
  'enter_email': 'Inserisci la tua email',
  'invalid_email': 'Indirizzo email non valido',
  'enter_password': 'Inserisci la tua password',
  'password_too_short': 'La password deve contenere almeno 6 caratteri',
  'enter_birth_date': 'Inserisci la tua data di nascita',
  'invalid_date': 'Formato data non valido',
  'enter_phone': 'Inserisci il tuo numero di telefono',
  'age_restriction': 'Devi avere almeno 18 anni',
  'auth_error': 'Errore di autenticazione',
  'account_created': 'Account creato con successo',
  'chats': 'Chat',
  'hub': 'Hub',
  'converter': 'Convertitore',
  'news': 'Notizie',
  'profile': 'Profilo',
  'export_data': 'Esporta dati utente',
  'send_data': 'Invia dati',
  'data_sent': 'Dati inviati con successo',
  'error_sending_data': 'Errore nell\'invio dei dati',
  'type_message': 'Scrivi il tuo messaggio...',
  'no_messages': 'Nessun messaggio ancora.\nSii il primo a inviare!',
  'error_loading_messages': 'Errore nel caricamento dei messaggi',
  'hello': 'Ciao',
  'portfolio': 'Portafoglio',
  'quick_actions': 'Azioni rapide',
  'send': 'Invia',
  'receive': 'Ricevi',
  'deposit': 'Deposita',
  'convert': 'Converti',
  'watchlist': 'Lista di controllo',
  'no_watchlists': 'Nessuna lista di controllo ancora',
  'recent_alerts': 'Avvisi recenti',
  'no_alerts': 'Nessun avviso ancora',
  'activities': 'Attività',
  'transactions': 'Transazioni',
  'orders': 'Ordini',
  'alerts': 'Avvisi',
  'reports': 'Rapporti',
  'no_transactions': 'Nessuna transazione ancora',
  'no_orders': 'Nessun ordine ancora',
  'generate_report': 'Genera rapporto',
  'feed': 'Feed',
  'create_post': 'Crea post',
  'write_post': 'Scrivi il tuo post...',
  'post': 'Pubblica',
  'marketplace': 'Mercato',
  'bio': 'Biografia',
  'update_bio': 'Aggiorna biografia',
  'statistics': 'Statistiche',
  'points': 'Punti',
  'followers': 'Follower',
  'settings': 'Impostazioni',
  'themes': 'Temi',
  'languages': 'Lingue',
  'integrations': 'Integrazioni',
  'security': 'Sicurezza',
  'logout': 'Esci',
  'charts': 'Grafici',
  'screener': 'Screener',
  'calculators': 'Calcolatrici',
  'journal': 'Diario',
  'strategies': 'Strategie',
  'backtesting': 'Backtesting',
  'paper_trading': 'Trading simulato',
  'reminders': 'Promemoria',
  'researcher': 'Ricercatore',
  'dictionary': 'Dizionario',
  'heatmaps': 'Mappe termiche',
  'correlation': 'Correlazione',
  'football': 'Calcio',
  'entertainment': 'Intrattenimento',
  'learning': 'Apprendimento',
  'webinars': 'Webinar',
  'add_indicator': 'Aggiungi indicatore',
  'filters': 'Filtri',
  'run_screener': 'Esegui screener',
  'results': 'Risultati',
  'position': 'Posizione',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Punti pivot',
  'risk_percentage': 'Percentuale di rischio',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calcola',
  'new_entry': 'Nuova voce',
  'add_entry': 'Aggiungi voce',
  'select_strategy': 'Seleziona strategia',
  'asset': 'Asset',
  'start_date': 'Data di inizio',
  'end_date': 'Data di fine',
  'run_backtest': 'Esegui backtest',
  'backtest_results': 'Risultati backtest',
  'balance': 'Saldo',
  'positions': 'Posizioni',
  'place_order': 'Effettua ordine',
  'buy': 'Compra',
  'sell': 'Vendi',
  'quantity': 'Quantità',
  'price': 'Prezzo',
  'title': 'Titolo',
  'date': 'Data',
  'add_reminder': 'Aggiungi promemoria',
  'search_query': 'Query di ricerca',
  'search': 'Cerca',
  'search_term': 'Termine di ricerca',
  'amount': 'Importo',
  'result': 'Risultato',
  'select_assets': 'Seleziona asset',
  'calculate_correlation': 'Calcola correlazione',
  'trading_simulator': 'Simulatore di trading',
  'score': 'Punteggio',
  'start_game': 'Inizia gioco',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz completato',
  'movies': 'Film',
  'menu': 'Menu',
  'error_loading': 'Errore nel caricamento dei dati',
  'close': 'Chiudi',
};