const Map<String, String> en = {
  'login': 'Login',
  'create_account': 'Create Account',
  'already_have_account': 'Already have an account? Login',
  'name': 'Name',
  'email': 'Email',
  'password': 'Password',
  'birth_date': 'Birth Date (YYYY-MM-DD)',
  'phone': 'Phone Number',
  'enter_name': 'Please enter your name',
  'enter_email': 'Please enter your email',
  'invalid_email': 'Invalid email address',
  'enter_password': 'Please enter your password',
  'password_too_short': 'Password must be at least 6 characters',
  'enter_birth_date': 'Please enter your birth date',
  'invalid_date': 'Invalid date format',
  'enter_phone': 'Please enter your phone number',
  'age_restriction': 'You must be at least 18 years old',
  'auth_error': 'Authentication error',
  'account_created': 'Account created successfully',
  'chats': 'Chats',
  'hub': 'Hub',
  'converter': 'Converter',
  'news': 'News',
  'profile': 'Profile',
  'export_data': 'Export User Data',
  'send_data': 'Send Data',
  'data_sent': 'Data sent successfully',
  'error_sending_data': 'Error sending data',
  'type_message': 'Type your message...',
  'no_messages': 'No messages yet.\nBe the first to send!',
  'error_loading_messages': 'Error loading messages',
  'hello': 'Hello',
  'portfolio': 'Portfolio',
  'quick_actions': 'Quick Actions',
  'send': 'Send',
  'receive': 'Receive',
  'deposit': 'Deposit',
  'convert': 'Convert',
  'watchlist': 'Watchlist',
  'no_watchlists': 'No watchlists yet',
  'recent_alerts': 'Recent Alerts',
  'no_alerts': 'No alerts yet',
  'activities': 'Activities',
  'transactions': 'Transactions',
  'orders': 'Orders',
  'alerts': 'Alerts',
  'reports': 'Reports',
  'no_transactions': 'No transactions yet',
  'no_orders': 'No orders yet',
  'generate_report': 'Generate Report',
  'feed': 'Feed',
  'create_post': 'Create Post',
  'write_post': 'Write your post...',
  'post': 'Post',
  'marketplace': 'Marketplace',
  'bio': 'Bio',
  'update_bio': 'Update Bio',
  'statistics': 'Statistics',
  'points': 'Points',
  'followers': 'Followers',
  'settings': 'Settings',
  'themes': 'Themes',
  'languages': 'Languages',
  'integrations': 'Integrations',
  'security': 'Security',
  'logout': 'Logout',
  'charts': 'Charts',
  'screener': 'Screener',
  'calculators': 'Calculators',
  'journal': 'Journal',
  'strategies': 'Strategies',
  'backtesting': 'Backtesting',
  'paper_trading': 'Paper Trading',
  'reminders': 'Reminders',
  'researcher': 'Researcher',
  'dictionary': 'Dictionary',
  'heatmaps': 'Heatmaps',
  'correlation': 'Correlation',
  'football': 'Football',
  'entertainment': 'Entertainment',
  'learning': 'Learning',
  'webinars': 'Webinars',
  'add_indicator': 'Add Indicator',
  'filters': 'Filters',
  'run_screener': 'Run Screener',
  'results': 'Results',
  'position': 'Position',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Pivot Points',
  'risk_percentage': 'Risk Percentage',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calculate',
  'new_entry': 'New Entry',
  'add_entry': 'Add Entry',
  'select_strategy': 'Select Strategy',
  'asset': 'Asset',
  'start_date': 'Start Date',
  'end_date': 'End Date',
  'run_backtest': 'Run Backtest',
  'backtest_results': 'Backtest Results',
  'balance': 'Balance',
  'positions': 'Positions',
  'place_order': 'Place Order',
  'buy': 'Buy',
  'sell': 'Sell',
  'quantity': 'Quantity',
  'price': 'Price',
  'title': 'Title',
  'date': 'Date',
  'add_reminder': 'Add Reminder',
  'search_query': 'Search Query',
  'search': 'Search',
  'search_term': 'Search Term',
  'amount': 'Amount',
  'result': 'Result',
  'select_assets': 'Select Assets',
  'calculate_correlation': 'Calculate Correlation',
  'trading_simulator': 'Trading Simulator',
  'score': 'Score',
  'start_game': 'Start Game',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz Complete',
  'movies': 'Movies',
  'menu': 'Menu',
  'error_loading': 'Error loading data',
  'close': 'Close',
  // Add all other keys from spec
};