const Map<String, String> de = {
  'login': 'Anmelden',
  'create_account': 'Konto erstellen',
  'already_have_account': 'Bereits ein Konto? Anmelden',
  'name': 'Name',
  'email': 'E-Mail',
  'password': 'Passwort',
  'birth_date': 'Geburtsdatum (JJJJ-MM-TT)',
  'phone': 'Telefonnummer',
  'enter_name': 'Bitte geben Sie Ihren Namen ein',
  'enter_email': 'Bitte geben Sie Ihre E-Mail ein',
  'invalid_email': 'Ungültige E-Mail-Adresse',
  'enter_password': 'Bitte geben Sie Ihr Passwort ein',
  'password_too_short': 'Passwort muss mindestens 6 Zeichen lang sein',
  'enter_birth_date': 'Bitte geben Sie Ihr Geburtsdatum ein',
  'invalid_date': 'Ungültiges Datumsformat',
  'enter_phone': 'Bitte geben Sie Ihre Telefonnummer ein',
  'age_restriction': 'Sie müssen mindestens 18 Jahre alt sein',
  'auth_error': 'Authentifizierungsfehler',
  'account_created': 'Konto erfolgreich erstellt',
  'chats': 'Chats',
  'hub': 'Hub',
  'converter': 'Konverter',
  'news': 'Nachrichten',
  'profile': 'Profil',
  'export_data': 'Benutzerdaten exportieren',
  'send_data': 'Daten senden',
  'data_sent': 'Daten erfolgreich gesendet',
  'error_sending_data': 'Fehler beim Senden der Daten',
  'type_message': 'Geben Sie Ihre Nachricht ein...',
  'no_messages': 'Noch keine Nachrichten.\nSeien Sie der Erste!',
  'error_loading_messages': 'Fehler beim Laden der Nachrichten',
  'hello': 'Hallo',
  'portfolio': 'Portfolio',
  'quick_actions': 'Schnellaktionen',
  'send': 'Senden',
  'receive': 'Empfangen',
  'deposit': 'Einzahlen',
  'convert': 'Konvertieren',
  'watchlist': 'Watchlist',
  'no_watchlists': 'Noch keine Watchlists',
  'recent_alerts': 'Aktuelle Benachrichtigungen',
  'no_alerts': 'Noch keine Benachrichtigungen',
  'activities': 'Aktivitäten',
  'transactions': 'Transaktionen',
  'orders': 'Aufträge',
  'alerts': 'Benachrichtigungen',
  'reports': 'Berichte',
  'no_transactions': 'Noch keine Transaktionen',
  'no_orders': 'Noch keine Aufträge',
  'generate_report': 'Bericht erstellen',
  'feed': 'Feed',
  'create_post': 'Beitrag erstellen',
  'write_post': 'Schreiben Sie Ihren Beitrag...',
  'post': 'Beitrag',
  'marketplace': 'Marktplatz',
  'bio': 'Biografie',
  'update_bio': 'Biografie aktualisieren',
  'statistics': 'Statistiken',
  'points': 'Punkte',
  'followers': 'Follower',
  'settings': 'Einstellungen',
  'themes': 'Themen',
  'languages': 'Sprachen',
  'integrations': 'Integrationen',
  'security': 'Sicherheit',
  'logout': 'Abmelden',
  'charts': 'Diagramme',
  'screener': 'Screener',
  'calculators': 'Rechner',
  'journal': 'Journal',
  'strategies': 'Strategien',
  'backtesting': 'Backtesting',
  'paper_trading': 'Papierhandel',
  'reminders': 'Erinnerungen',
  'researcher': 'Forscher',
  'dictionary': 'Wörterbuch',
  'heatmaps': 'Heatmaps',
  'correlation': 'Korrelation',
  'football': 'Fußball',
  'entertainment': 'Unterhaltung',
  'learning': 'Lernen',
  'webinars': 'Webinare',
  'add_indicator': 'Indikator hinzufügen',
  'filters': 'Filter',
  'run_screener': 'Screener ausführen',
  'results': 'Ergebnisse',
  'position': 'Position',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Pivot-Punkte',
  'risk_percentage': 'Risikoprozentsatz',
  'stop_loss': 'Stop-Loss',
  'calculate': 'Berechnen',
  'new_entry': 'Neuer Eintrag',
  'add_entry': 'Eintrag hinzufügen',
  'select_strategy': 'Strategie auswählen',
  'asset': 'Vermögenswert',
  'start_date': 'Startdatum',
  'end_date': 'Enddatum',
  'run_backtest': 'Backtest ausführen',
  'backtest_results': 'Backtest-Ergebnisse',
  'balance': 'Guthaben',
  'positions': 'Positionen',
  'place_order': 'Auftrag erteilen',
  'buy': 'Kaufen',
  'sell': 'Verkaufen',
  'quantity': 'Menge',
  'price': 'Preis',
  'title': 'Titel',
  'date': 'Datum',
  'add_reminder': 'Erinnerung hinzufügen',
  'search_query': 'Suchanfrage',
  'search': 'Suchen',
  'search_term': 'Suchbegriff',
  'amount': 'Betrag',
  'result': 'Ergebnis',
  'select_assets': 'Vermögenswerte auswählen',
  'calculate_correlation': 'Korrelation berechnen',
  'trading_simulator': 'Handelssimulator',
  'score': 'Punktzahl',
  'start_game': 'Spiel starten',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz abgeschlossen',
  'movies': 'Filme',
  'menu': 'Menü',
  'error_loading': 'Fehler beim Laden der Daten',
  'close': 'Schließen',
};