const Map<String, String> pt = {
  'login': 'Entrar',
  'create_account': 'Criar conta',
  'already_have_account': 'Já tem uma conta? Entrar',
  'name': 'Nome',
  'email': 'Email',
  'password': 'Senha',
  'birth_date': 'Data de nascimento (AAAA-MM-DD)',
  'phone': 'Número de telefone',
  'enter_name': 'Digite seu nome',
  'enter_email': 'Digite seu email',
  'invalid_email': 'Endereço de email inválido',
  'enter_password': 'Digite sua senha',
  'password_too_short': 'A senha deve ter pelo menos 6 caracteres',
  'enter_birth_date': 'Digite sua data de nascimento',
  'invalid_date': 'Formato de data inválido',
  'enter_phone': 'Digite seu número de telefone',
  'age_restriction': 'Você deve ter pelo menos 18 anos',
  'auth_error': 'Erro de autenticação',
  'account_created': 'Conta criada com sucesso',
  'chats': 'Conversas',
  'hub': 'Central',
  'converter': 'Conversor',
  'news': 'Notícias',
  'profile': 'Perfil',
  'export_data': 'Exportar dados do usuário',
  'send_data': 'Enviar dados',
  'data_sent': 'Dados enviados com sucesso',
  'error_sending_data': 'Erro ao enviar dados',
  'type_message': 'Digite sua mensagem...',
  'no_messages': 'Ainda não há mensagens.\nSeja o primeiro a enviar!',
  'error_loading_messages': 'Erro ao carregar mensagens',
  'hello': 'Olá',
  'portfolio': 'Portfólio',
  'quick_actions': 'Ações rápidas',
  'send': 'Enviar',
  'receive': 'Receber',
  'deposit': 'Depósito',
  'convert': 'Converter',
  'watchlist': 'Lista de observação',
  'no_watchlists': 'Ainda não há listas de observação',
  'recent_alerts': 'Alertas recentes',
  'no_alerts': 'Ainda não há alertas',
  'activities': 'Atividades',
  'transactions': 'Transações',
  'orders': 'Ordens',
  'alerts': 'Alertas',
  'reports': 'Relatórios',
  'no_transactions': 'Ainda não há transações',
  'no_orders': 'Ainda não há ordens',
  'generate_report': 'Gerar relatório',
  'feed': 'Feed',
  'create_post': 'Criar publicação',
  'write_post': 'Escreva sua publicação...',
  'post': 'Publicar',
  'marketplace': 'Mercado',
  'bio': 'Biografia',
  'update_bio': 'Atualizar biografia',
  'statistics': 'Estatísticas',
  'points': 'Pontos',
  'followers': 'Seguidores',
  'settings': 'Configurações',
  'themes': 'Temas',
  'languages': 'Idiomas',
  'integrations': 'Integrações',
  'security': 'Segurança',
  'logout': 'Sair',
  'charts': 'Gráficos',
  'screener': 'Rastreador',
  'calculators': 'Calculadoras',
  'journal': 'Diário',
  'strategies': 'Estratégias',
  'backtesting': 'Backtesting',
  'paper_trading': 'Negociação simulada',
  'reminders': 'Lembretes',
  'researcher': 'Pesquisador',
  'dictionary': 'Dicionário',
  'heatmaps': 'Mapas de calor',
  'correlation': 'Correlação',
  'football': 'Futebol',
  'entertainment': 'Entretenimento',
  'learning': 'Aprendizado',
  'webinars': 'Webinars',
  'add_indicator': 'Adicionar indicador',
  'filters': 'Filtros',
  'run_screener': 'Executar rastreador',
  'results': 'Resultados',
  'position': 'Posição',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Pontos de pivô',
  'risk_percentage': 'Percentual de risco',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calcular',
  'new_entry': 'Nova entrada',
  'add_entry': 'Adicionar entrada',
  'select_strategy': 'Selecionar estratégia',
  'asset': 'Ativo',
  'start_date': 'Data de início',
  'end_date': 'Data de término',
  'run_backtest': 'Executar backtest',
  'backtest_results': 'Resultados do backtest',
  'balance': 'Saldo',
  'positions': 'Posições',
  'place_order': 'Colocar ordem',
  'buy': 'Comprar',
  'sell': 'Vender',
  'quantity': 'Quantidade',
  'price': 'Preço',
  'title': 'Título',
  'date': 'Data',
  'add_reminder': 'Adicionar lembrete',
  'search_query': 'Consulta de pesquisa',
  'search': 'Pesquisar',
  'search_term': 'Termo de pesquisa',
  'amount': 'Valor',
  'result': 'Resultado',
  'select_assets': 'Selecionar ativos',
  'calculate_correlation': 'Calcular correlação',
  'trading_simulator': 'Simulador de negociação',
  'score': 'Pontuação',
  'start_game': 'Iniciar jogo',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz concluído',
  'movies': 'Filmes',
  'menu': 'Menu',
  'error_loading': 'Erro ao carregar dados',
  'close': 'Fechar',
  'send_receive': 'Enviar/Receber',
  'notifications': 'Notificações',
  'performance_chart': 'Gráfico de desempenho',
  'order_book': 'Livro de ordens',
  'condition': 'Condição',
  'status': 'Status',
  'description': 'Descrição',
  'timestamp': 'Timestamp',
  'type': 'Tipo',
  'active': 'Ativo',
  'triggered': 'Acionado',
  'cancel': 'Cancelar',
  'save': 'Salvar',
  'edit': 'Editar',
  'delete': 'Excluir',
  'confirm': 'Confirmar',
  'success': 'Sucesso',
  'error': 'Erro',
  'warning': 'Aviso',
  'info': 'Informação',
  'loading': 'Carregando...',
  'no_data': 'Sem dados disponíveis',
  'refresh': 'Atualizar',
  'filter': 'Filtrar',
  'sort': 'Ordenar',
  'ascending': 'Crescente',
  'descending': 'Decrescente',
  'all': 'Todos',
  'none': 'Nenhum',
  'select': 'Selecionar',
  'selected': 'Selecionado',
  'deselect': 'Desmarcar',
  'apply': 'Aplicar',
  'reset': 'Redefinir',
  'clear': 'Limpar',
  'done': 'Concluído',
  'next': 'Próximo',
  'previous': 'Anterior',
  'skip': 'Pular',
  'finish': 'Finalizar',
  'yes': 'Sim',
  'no': 'Não',
  'ok': 'OK',
  'got_it': 'Entendi',
  'learn_more': 'Saiba mais',
  'see_all': 'Ver todos',
  'show_more': 'Mostrar mais',
  'show_less': 'Mostrar menos',
  'expand': 'Expandir',
  'collapse': 'Recolher',
  'open': 'Abrir',
  'share': 'Compartilhar',
  'copy': 'Copiar',
  'paste': 'Colar',
  'cut': 'Recortar',
  'undo': 'Desfazer',
  'redo': 'Refazer',
  'upload': 'Enviar',
  'download': 'Baixar',
  'print': 'Imprimir',
  'preview': 'Visualizar',
  'view': 'Ver',
  'details': 'Detalhes',
  'more': 'Mais',
  'less': 'Menos',
  'help': 'Ajuda',
  'about': 'Sobre',
  'version': 'Versão',
  'terms': 'Termos',
  'privacy': 'Privacidade',
  'contact': 'Contato',
  'support': 'Suporte',
  'feedback': 'Feedback',
  'rate_app': 'Avaliar app',
  'update': 'Atualizar',
  'new_version': 'Nova versão',
  'required': 'Obrigatório',
  'optional': 'Opcional',
  'recommended': 'Recomendado',
  'popular': 'Popular',
  'trending': 'Em alta',
  'new': 'Novo',
  'featured': 'Destaque',
  'top': 'Top',
  'best': 'Melhor',
  'latest': 'Mais recente',
  'recent': 'Recente',
  'today': 'Hoje',
  'yesterday': 'Ontem',
  'this_week': 'Esta semana',
  'this_month': 'Este mês',
  'this_year': 'Este ano',
  'last_week': 'Semana passada',
  'last_month': 'Mês passado',
  'last_year': 'Ano passado',
  'custom': 'Personalizado',
  'default': 'Padrão',
  'enabled': 'Ativado',
  'disabled': 'Desativado',
  'on': 'Ligado',
  'off': 'Desligado',
  'automatic': 'Automático',
  'manual': 'Manual',
  'always': 'Sempre',
  'never': 'Nunca',
  'ask': 'Perguntar',
  'light': 'Claro',
  'dark': 'Escuro',
  'system': 'Sistema',
  'high': 'Alto',
  'medium': 'Médio',
  'low': 'Baixo',
  'very_high': 'Muito alto',
  'very_low': 'Muito baixo',
  'maximum': 'Máximo',
  'minimum': 'Mínimo',
  'unlimited': 'Ilimitado',
  'limited': 'Limitado',
  'free': 'Grátis',
  'premium': 'Premium',
  'pro': 'Pro',
  'basic': 'Básico',
  'standard': 'Padrão',
  'advanced': 'Avançado',
  'beginner': 'Iniciante',
  'intermediate': 'Intermediário',
  'expert': 'Especialista',
  'easy': 'Fácil',
  'normal': 'Normal',
  'hard': 'Difícil',
  'complete': 'Completo',
  'incomplete': 'Incompleto',
  'pending': 'Pendente',
  'approved': 'Aprovado',
  'rejected': 'Rejeitado',
  'cancelled': 'Cancelado',
  'failed': 'Falhou',
  'processing': 'Processando',
  'completed': 'Concluído',
  'verified': 'Verificado',
  'unverified': 'Não verificado',
  'connected': 'Conectado',
  'disconnected': 'Desconectado',
  'online': 'Online',
  'offline': 'Offline',
  'available': 'Disponível',
  'unavailable': 'Indisponível',
  'in_stock': 'Em estoque',
  'out_of_stock': 'Fora de estoque',
  'coming_soon': 'Em breve',
  'maintenance': 'Manutenção',
  'emergency': 'Emergência',
  'scheduled': 'Agendado',
  'unscheduled': 'Não agendado',
  'public': 'Público',
  'private': 'Privado',
  'draft': 'Rascunho',
  'published': 'Publicado',
  'archived': 'Arquivado',
  'deleted': 'Excluído',
  'restored': 'Restaurado',
  'backup': 'Backup',
  'import': 'Importar',
  'export': 'Exportar',
  'sync': 'Sincronizar',
  'syncing': 'Sincronizando',
  'synced': 'Sincronizado',
  'not_synced': 'Não sincronizado',
  'sync_failed': 'Sincronização falhou',
  'retry': 'Tentar novamente',
  'try_again': 'Tentar novamente',
  'continue': 'Continuar',
  'back': 'Voltar',
  'home': 'Início',
  'dashboard': 'Painel',
  'overview': 'Visão geral',
  'summary': 'Resumo',
  'list': 'Lista',
  'grid': 'Grade',
  'table': 'Tabela',
  'calendar': 'Calendário',
  'map': 'Mapa',
  'graph': 'Gráfico',
  'chart': 'Gráfico',
  'report': 'Relatório',
  'analytics': 'Análises',
  'insights': 'Insights',
  'trends': 'Tendências',
  'comparison': 'Comparação',
  'performance': 'Desempenho',
  'growth': 'Crescimento',
  'decline': 'Declínio',
  'change': 'Mudança',
  'increase': 'Aumento',
  'decrease': 'Diminuição',
  'percentage': 'Porcentagem',
  'value': 'Valor',
  'total': 'Total',
  'subtotal': 'Subtotal',
  'average': 'Média',
  'median': 'Mediana',
  'mode': 'Moda',
  'range': 'Intervalo',
  'sum': 'Soma',
  'count': 'Contagem',
  'frequency': 'Frequência',
  'rate': 'Taxa',
  'ratio': 'Razão',
  'profit': 'Lucro',
  'loss': 'Perda',
  'revenue': 'Receita',
  'expense': 'Despesa',
  'income': 'Renda',
  'cost': 'Custo',
  'fee': 'Taxa',
  'tax': 'Imposto',
  'discount': 'Desconto',
  'commission': 'Comissão',
  'interest': 'Juros',
  'dividend': 'Dividendo',
  'bonus': 'Bônus',
  'reward': 'Recompensa',
  'penalty': 'Penalidade',
  'credit': 'Crédito',
  'debit': 'Débito',
  'payment': 'Pagamento',
  'refund': 'Reembolso',
  'withdrawal': 'Saque',
  'transfer': 'Transferência',
  'exchange': 'Câmbio',
  'trade': 'Negociação',
  'investment': 'Investimento',
  'savings': 'Poupança',
  'account': 'Conta',
  'wallet': 'Carteira',
  'card': 'Cartão',
  'bank': 'Banco',
  'currency': 'Moeda',
  'crypto': 'Cripto',
  'stock': 'Ação',
  'bond': 'Título',
  'commodity': 'Commodity',
  'forex': 'Forex',
  'index': 'Índice',
  'etf': 'ETF',
  'mutual_fund': 'Fundo mútuo',
  'real_estate': 'Imóveis',
  'option': 'Opção',
  'future': 'Futuro',
  'derivative': 'Derivativo',
  'security': 'Título',
  'instrument': 'Instrumento',
  'market': 'Mercado',
  'exchange_market': 'Bolsa',
  'broker': 'Corretora',
  'dealer': 'Distribuidor',
  'trader': 'Trader',
  'investor': 'Investidor',
  'buyer': 'Comprador',
  'seller': 'Vendedor',
  'bid': 'Oferta',
  'ask': 'Pedido',
  'spread': 'Spread',
  'volume': 'Volume',
  'liquidity': 'Liquidez',
  'volatility': 'Volatilidade',
  'trend': 'Tendência',
  'bullish': 'Alta',
  'bearish': 'Baixa',
  'neutral': 'Neutro',
  'support': 'Suporte',
  'resistance': 'Resistência',
  'breakout': 'Rompimento',
  'breakdown': 'Queda',
  'reversal': 'Reversão',
  'continuation': 'Continuação',
  'pattern': 'Padrão',
  'signal': 'Sinal',
  'indicator': 'Indicador',
  'oscillator': 'Oscilador',
  'moving_average': 'Média móvel',
  'rsi': 'RSI',
  'macd': 'MACD',
  'bollinger_bands': 'Bandas de Bollinger',
  'stochastic': 'Estocástico',
  'adx': 'ADX',
  'atr': 'ATR',
  'cci': 'CCI',
  'williams_r': 'Williams %R',
  'momentum': 'Momentum',
  'roc': 'ROC',
  'obv': 'OBV',
  'vwap': 'VWAP',
  'ema': 'EMA',
  'sma': 'SMA',
  'wma': 'WMA',
  'hma': 'HMA',
  'ichimoku': 'Ichimoku',
  'parabolic_sar': 'SAR Parabólico',
  'keltner_channels': 'Canais de Keltner',
  'donchian_channels': 'Canais de Donchian',
  'envelope': 'Envelope',
  'alligator': 'Alligator',
  'fractals': 'Fractais',
  'gator': 'Gator',
  'awesome_oscillator': 'Oscilador Awesome',
  'accelerator': 'Acelerador',
  'market_facilitation': 'Facilitação de mercado',
  'zigzag': 'ZigZag',
  'elliott_wave': 'Onda de Elliott',
  'gann': 'Gann',
  'andrews_pitchfork': 'Pitchfork de Andrews',
  'trendline': 'Linha de tendência',
  'channel': 'Canal',
  'rectangle': 'Retângulo',
  'triangle': 'Triângulo',
  'wedge': 'Cunha',
  'flag': 'Bandeira',
  'pennant': 'Flâmula',
  'head_shoulders': 'Ombro-cabeça-ombro',
  'double_top': 'Topo duplo',
  'double_bottom': 'Fundo duplo',
  'triple_top': 'Topo triplo',
  'triple_bottom': 'Fundo triplo',
  'cup_handle': 'Xícara com alça',
  'rounding_bottom': 'Fundo arredondado',
  'ascending_triangle': 'Triângulo ascendente',
  'descending_triangle': 'Triângulo descendente',
  'symmetrical_triangle': 'Triângulo simétrico',
  'rising_wedge': 'Cunha ascendente',
  'falling_wedge': 'Cunha descendente',
  'bull_flag': 'Bandeira de alta',
  'bear_flag': 'Bandeira de baixa',
  'bull_pennant': 'Flâmula de alta',
  'bear_pennant': 'Flâmula de baixa',
  'gap': 'Gap',
  'island_reversal': 'Reversão em ilha',
  'candlestick': 'Candlestick',
  'doji': 'Doji',
  'hammer': 'Martelo',
  'hanging_man': 'Enforcado',
  'shooting_star': 'Estrela cadente',
  'inverted_hammer': 'Martelo invertido',
  'engulfing': 'Engolfo',
  'harami': 'Harami',
  'piercing': 'Perfurante',
  'dark_cloud': 'Nuvem negra',
  'morning_star': 'Estrela da manhã',
  'evening_star': 'Estrela da noite',
  'three_white_soldiers': 'Três soldados brancos',
  'three_black_crows': 'Três corvos pretos',
  'spinning_top': 'Pião',
  'marubozu': 'Marubozu',
  'tweezer': 'Pinça',
  'abandoned_baby': 'Bebê abandonado',
  'three_inside': 'Três internos',
  'three_outside': 'Três externos',
  'rising_three': 'Três ascendentes',
  'falling_three': 'Três descendentes',
  'upside_gap': 'Gap de alta',
  'downside_gap': 'Gap de baixa',
  'kicking': 'Chute',
  'ladder': 'Escada',
  'three_line_strike': 'Ataque de três linhas',
  'two_crows': 'Dois corvos',
  'unique_three_river': 'Três rios únicos',
  'concealing_baby_swallow': 'Andorinha bebê escondida',
  'stick_sandwich': 'Sanduíche de bastão',
  'matching_low': 'Baixa correspondente',
  'homing_pigeon': 'Pombo-correio',
  'ladder_bottom': 'Escada inferior',
  'belt_hold': 'Segurar cinto',
  'upside_tasuki_gap': 'Gap Tasuki de alta',
  'downside_tasuki_gap': 'Gap Tasuki de baixa',
  'side_by_side': 'Lado a lado',
  'separating_lines': 'Linhas de separação',
  'in_neck': 'No pescoço',
  'on_neck': 'Sobre o pescoço',
  'thrusting': 'Empurrão',
  'mat_hold': 'Segurar tapete',
  'breakaway': 'Fuga',
  'three_stars_south': 'Três estrelas do sul',
  'deliberation': 'Deliberação',
  'advance_block': 'Bloco avançado',
  'stalled_pattern': 'Padrão estagnado',
  'doji_star': 'Estrela Doji',
  'dragonfly_doji': 'Doji libélula',
  'gravestone_doji': 'Doji lápide',
  'long_legged_doji': 'Doji de pernas longas',
  'rickshaw_man': 'Homem riquixá',
  'high_wave': 'Onda alta',
  'counterattack': 'Contra-ataque',
  'meeting_lines': 'Linhas de encontro',
};