const Map<String, String> fr = {
  'login': 'Se connecter',
  'create_account': 'Créer un compte',
  'already_have_account': 'Vous avez déjà un compte ? Se connecter',
  'name': 'Nom',
  'email': 'Email',
  'password': 'Mot de passe',
  'birth_date': 'Date de naissance (AAAA-MM-JJ)',
  'phone': 'Numéro de téléphone',
  'enter_name': 'Veuillez entrer votre nom',
  'enter_email': 'Veuillez entrer votre email',
  'invalid_email': 'Adresse email invalide',
  'enter_password': 'Veuillez entrer votre mot de passe',
  'password_too_short': 'Le mot de passe doit contenir au moins 6 caractères',
  'enter_birth_date': 'Veuillez entrer votre date de naissance',
  'invalid_date': 'Format de date invalide',
  'enter_phone': 'Veuillez entrer votre numéro de téléphone',
  'age_restriction': 'Vous devez avoir au moins 18 ans',
  'auth_error': 'Erreur d\'authentification',
  'account_created': 'Compte créé avec succès',
  'chats': 'Chats',
  'hub': 'Hub',
  'converter': 'Convertisseur',
  'news': 'Actualités',
  'profile': 'Profil',
  'export_data': 'Exporter les données utilisateur',
  'send_data': 'Envoyer les données',
  'data_sent': 'Données envoyées avec succès',
  'error_sending_data': 'Erreur lors de l\'envoi des données',
  'type_message': 'Tapez votre message...',
  'no_messages': 'Pas encore de messages.\nSoyez le premier à envoyer !',
  'error_loading_messages': 'Erreur lors du chargement des messages',
  'hello': 'Bonjour',
  'portfolio': 'Portefeuille',
  'quick_actions': 'Actions rapides',
  'send': 'Envoyer',
  'receive': 'Recevoir',
  'deposit': 'Déposer',
  'convert': 'Convertir',
  'watchlist': 'Liste de surveillance',
  'no_watchlists': 'Pas encore de listes de surveillance',
  'recent_alerts': 'Alertes récentes',
  'no_alerts': 'Pas encore d\'alertes',
  'activities': 'Activités',
  'transactions': 'Transactions',
  'orders': 'Ordres',
  'alerts': 'Alertes',
  'reports': 'Rapports',
  'no_transactions': 'Pas encore de transactions',
  'no_orders': 'Pas encore d\'ordres',
  'generate_report': 'Générer un rapport',
  'feed': 'Fil d\'actualité',
  'create_post': 'Créer une publication',
  'write_post': 'Écrivez votre publication...',
  'post': 'Publier',
  'marketplace': 'Marché',
  'bio': 'Biographie',
  'update_bio': 'Mettre à jour la biographie',
  'statistics': 'Statistiques',
  'points': 'Points',
  'followers': 'Abonnés',
  'settings': 'Paramètres',
  'themes': 'Thèmes',
  'languages': 'Langues',
  'integrations': 'Intégrations',
  'security': 'Sécurité',
  'logout': 'Se déconnecter',
  'charts': 'Graphiques',
  'screener': 'Screener',
  'calculators': 'Calculatrices',
  'journal': 'Journal',
  'strategies': 'Stratégies',
  'backtesting': 'Backtesting',
  'paper_trading': 'Trading papier',
  'reminders': 'Rappels',
  'researcher': 'Chercheur',
  'dictionary': 'Dictionnaire',
  'heatmaps': 'Cartes thermiques',
  'correlation': 'Corrélation',
  'football': 'Football',
  'entertainment': 'Divertissement',
  'learning': 'Apprentissage',
  'webinars': 'Webinaires',
  'add_indicator': 'Ajouter un indicateur',
  'filters': 'Filtres',
  'run_screener': 'Exécuter le screener',
  'results': 'Résultats',
  'position': 'Position',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Points pivots',
  'risk_percentage': 'Pourcentage de risque',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calculer',
  'new_entry': 'Nouvelle entrée',
  'add_entry': 'Ajouter une entrée',
  'select_strategy': 'Sélectionner une stratégie',
  'asset': 'Actif',
  'start_date': 'Date de début',
  'end_date': 'Date de fin',
  'run_backtest': 'Exécuter le backtest',
  'backtest_results': 'Résultats du backtest',
  'balance': 'Solde',
  'positions': 'Positions',
  'place_order': 'Passer un ordre',
  'buy': 'Acheter',
  'sell': 'Vendre',
  'quantity': 'Quantité',
  'price': 'Prix',
  'title': 'Titre',
  'date': 'Date',
  'add_reminder': 'Ajouter un rappel',
  'search_query': 'Requête de recherche',
  'search': 'Rechercher',
  'search_term': 'Terme de recherche',
  'amount': 'Montant',
  'result': 'Résultat',
  'select_assets': 'Sélectionner des actifs',
  'calculate_correlation': 'Calculer la corrélation',
  'trading_simulator': 'Simulateur de trading',
  'score': 'Score',
  'start_game': 'Démarrer le jeu',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz terminé',
  'movies': 'Films',
  'menu': 'Menu',
  'error_loading': 'Erreur de chargement des données',
  'close': 'Fermer',
};