const Map<String, String> de = {
  'login': 'Anmelden',
  'create_account': 'Konto erstellen',
  'already_have_account': 'Haben Sie bereits ein Konto? Anmelden',
  'name': 'Name',
  'email': 'E-Mail',
  'password': 'Passwort',
  'birth_date': 'Geburtsdatum (JJJJ-MM-TT)',
  'phone': 'Telefonnummer',
  'enter_name': 'Bitte geben Sie Ihren Namen ein',
  'enter_email': 'Bitte geben Sie Ihre E-Mail ein',
  'invalid_email': 'Ungültige E-Mail-Adresse',
  'enter_password': 'Bitte geben Sie Ihr Passwort ein',
  'password_too_short': 'Passwort muss mindestens 6 Zeichen lang sein',
  'enter_birth_date': 'Bitte geben Sie Ihr Geburtsdatum ein',
  'invalid_date': 'Ungültiges Datumsformat',
  'enter_phone': 'Bitte geben Sie Ihre Telefonnummer ein',
  'age_restriction': 'Sie müssen mindestens 18 Jahre alt sein',
  'auth_error': 'Authentifizierungsfehler',
  'account_created': 'Konto erfolgreich erstellt',
  'chats': 'Chats',
  'hub': 'Hub',
  'converter': 'Konverter',
  'news': 'Nachrichten',
  'profile': 'Profil',
  'export_data': 'Benutzerdaten exportieren',
  'send_data': 'Daten senden',
  'data_sent': 'Daten erfolgreich gesendet',
  'error_sending_data': 'Fehler beim Senden der Daten',
  'type_message': 'Geben Sie Ihre Nachricht ein...',
  'no_messages': 'Noch keine Nachrichten.\nSeien Sie der Erste, der sendet!',
  'error_loading_messages': 'Fehler beim Laden der Nachrichten',
  'hello': 'Hallo',
  'portfolio': 'Portfolio',
  'quick_actions': 'Schnellaktionen',
  'send': 'Senden',
  'receive': 'Empfangen',
  'deposit': 'Einzahlung',
  'convert': 'Konvertieren',
  'watchlist': 'Watchlist',
  'no_watchlists': 'Noch keine Watchlists',
  'recent_alerts': 'Aktuelle Benachrichtigungen',
  'no_alerts': 'Noch keine Benachrichtigungen',
  'activities': 'Aktivitäten',
  'transactions': 'Transaktionen',
  'orders': 'Bestellungen',
  'alerts': 'Benachrichtigungen',
  'reports': 'Berichte',
  'no_transactions': 'Noch keine Transaktionen',
  'no_orders': 'Noch keine Bestellungen',
  'generate_report': 'Bericht erstellen',
  'feed': 'Feed',
  'create_post': 'Beitrag erstellen',
  'write_post': 'Schreiben Sie Ihren Beitrag...',
  'post': 'Beitrag',
  'marketplace': 'Marktplatz',
  'bio': 'Biografie',
  'update_bio': 'Biografie aktualisieren',
  'statistics': 'Statistiken',
  'points': 'Punkte',
  'followers': 'Follower',
  'settings': 'Einstellungen',
  'themes': 'Themen',
  'languages': 'Sprachen',
  'integrations': 'Integrationen',
  'security': 'Sicherheit',
  'logout': 'Abmelden',
  'charts': 'Diagramme',
  'screener': 'Screener',
  'calculators': 'Rechner',
  'journal': 'Journal',
  'strategies': 'Strategien',
  'backtesting': 'Backtesting',
  'paper_trading': 'Papierhandel',
  'reminders': 'Erinnerungen',
  'researcher': 'Forscher',
  'dictionary': 'Wörterbuch',
  'heatmaps': 'Heatmaps',
  'correlation': 'Korrelation',
  'football': 'Fußball',
  'entertainment': 'Unterhaltung',
  'learning': 'Lernen',
  'webinars': 'Webinare',
  'add_indicator': 'Indikator hinzufügen',
  'filters': 'Filter',
  'run_screener': 'Screener ausführen',
  'results': 'Ergebnisse',
  'position': 'Position',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Pivot-Punkte',
  'risk_percentage': 'Risikoprozentsatz',
  'stop_loss': 'Stop-Loss',
  'calculate': 'Berechnen',
  'new_entry': 'Neuer Eintrag',
  'add_entry': 'Eintrag hinzufügen',
  'select_strategy': 'Strategie auswählen',
  'asset': 'Vermögenswert',
  'start_date': 'Startdatum',
  'end_date': 'Enddatum',
  'run_backtest': 'Backtest ausführen',
  'backtest_results': 'Backtest-Ergebnisse',
  'balance': 'Saldo',
  'positions': 'Positionen',
  'place_order': 'Bestellung aufgeben',
  'buy': 'Kaufen',
  'sell': 'Verkaufen',
  'quantity': 'Menge',
  'price': 'Preis',
  'title': 'Titel',
  'date': 'Datum',
  'add_reminder': 'Erinnerung hinzufügen',
  'search_query': 'Suchanfrage',
  'search': 'Suchen',
  'search_term': 'Suchbegriff',
  'amount': 'Betrag',
  'result': 'Ergebnis',
  'select_assets': 'Vermögenswerte auswählen',
  'calculate_correlation': 'Korrelation berechnen',
  'trading_simulator': 'Handelssimulator',
  'score': 'Punktzahl',
  'start_game': 'Spiel starten',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz abgeschlossen',
  'movies': 'Filme',
  'menu': 'Menü',
  'error_loading': 'Fehler beim Laden der Daten',
  'close': 'Schließen',
  'send_receive': 'Senden/Empfangen',
  'notifications': 'Benachrichtigungen',
  'performance_chart': 'Leistungsdiagramm',
  'order_book': 'Orderbuch',
  'condition': 'Bedingung',
  'status': 'Status',
  'description': 'Beschreibung',
  'timestamp': 'Zeitstempel',
  'type': 'Typ',
  'active': 'Aktiv',
  'triggered': 'Ausgelöst',
  'cancel': 'Abbrechen',
  'save': 'Speichern',
  'edit': 'Bearbeiten',
  'delete': 'Löschen',
  'confirm': 'Bestätigen',
  'success': 'Erfolg',
  'error': 'Fehler',
  'warning': 'Warnung',
  'info': 'Information',
  'loading': 'Laden...',
  'no_data': 'Keine Daten verfügbar',
  'refresh': 'Aktualisieren',
  'filter': 'Filtern',
  'sort': 'Sortieren',
  'ascending': 'Aufsteigend',
  'descending': 'Absteigend',
  'all': 'Alle',
  'none': 'Keine',
  'select': 'Auswählen',
  'selected': 'Ausgewählt',
  'deselect': 'Abwählen',
  'apply': 'Anwenden',
  'reset': 'Zurücksetzen',
  'clear': 'Löschen',
  'done': 'Fertig',
  'next': 'Weiter',
  'previous': 'Zurück',
  'skip': 'Überspringen',
  'finish': 'Beenden',
  'yes': 'Ja',
  'no': 'Nein',
  'ok': 'OK',
  'got_it': 'Verstanden',
  'learn_more': 'Mehr erfahren',
  'see_all': 'Alle anzeigen',
  'show_more': 'Mehr anzeigen',
  'show_less': 'Weniger anzeigen',
  'expand': 'Erweitern',
  'collapse': 'Einklappen',
  'open': 'Öffnen',
  'share': 'Teilen',
  'copy': 'Kopieren',
  'paste': 'Einfügen',
  'cut': 'Ausschneiden',
  'undo': 'Rückgängig',
  'redo': 'Wiederholen',
  'upload': 'Hochladen',
  'download': 'Herunterladen',
  'print': 'Drucken',
  'preview': 'Vorschau',
  'view': 'Ansehen',
  'details': 'Details',
  'more': 'Mehr',
  'less': 'Weniger',
  'help': 'Hilfe',
  'about': 'Über',
  'version': 'Version',
  'terms': 'Nutzungsbedingungen',
  'privacy': 'Datenschutz',
  'contact': 'Kontakt',
  'support': 'Support',
  'feedback': 'Feedback',
  'rate_app': 'App bewerten',
  'update': 'Aktualisieren',
  'new_version': 'Neue Version',
  'required': 'Erforderlich',
  'optional': 'Optional',
  'recommended': 'Empfohlen',
  'popular': 'Beliebt',
  'trending': 'Im Trend',
  'new': 'Neu',
  'featured': 'Hervorgehoben',
  'top': 'Top',
  'best': 'Beste',
  'latest': 'Neueste',
  'recent': 'Kürzlich',
  'today': 'Heute',
  'yesterday': 'Gestern',
  'this_week': 'Diese Woche',
  'this_month': 'Dieser Monat',
  'this_year': 'Dieses Jahr',
  'last_week': 'Letzte Woche',
  'last_month': 'Letzter Monat',
  'last_year': 'Letztes Jahr',
  'custom': 'Benutzerdefiniert',
  'default': 'Standard',
  'enabled': 'Aktiviert',
  'disabled': 'Deaktiviert',
  'on': 'An',
  'off': 'Aus',
  'automatic': 'Automatisch',
  'manual': 'Manuell',
  'always': 'Immer',
  'never': 'Nie',
  'ask': 'Fragen',
  'light': 'Hell',
  'dark': 'Dunkel',
  'system': 'System',
  'high': 'Hoch',
  'medium': 'Mittel',
  'low': 'Niedrig',
  'very_high': 'Sehr hoch',
  'very_low': 'Sehr niedrig',
  'maximum': 'Maximum',
  'minimum': 'Minimum',
  'unlimited': 'Unbegrenzt',
  'limited': 'Begrenzt',
  'free': 'Kostenlos',
  'premium': 'Premium',
  'pro': 'Pro',
  'basic': 'Basis',
  'standard': 'Standard',
  'advanced': 'Erweitert',
  'beginner': 'Anfänger',
  'intermediate': 'Fortgeschritten',
  'expert': 'Experte',
  'easy': 'Einfach',
  'normal': 'Normal',
  'hard': 'Schwer',
  'complete': 'Abgeschlossen',
  'incomplete': 'Unvollständig',
  'pending': 'Ausstehend',
  'approved': 'Genehmigt',
  'rejected': 'Abgelehnt',
  'cancelled': 'Storniert',
  'failed': 'Fehlgeschlagen',
  'processing': 'Verarbeitung',
  'completed': 'Abgeschlossen',
  'verified': 'Verifiziert',
  'unverified': 'Nicht verifiziert',
  'connected': 'Verbunden',
  'disconnected': 'Getrennt',
  'online': 'Online',
  'offline': 'Offline',
  'available': 'Verfügbar',
  'unavailable': 'Nicht verfügbar',
  'in_stock': 'Auf Lager',
  'out_of_stock': 'Nicht auf Lager',
  'coming_soon': 'Bald verfügbar',
  'maintenance': 'Wartung',
  'emergency': 'Notfall',
  'scheduled': 'Geplant',
  'unscheduled': 'Ungeplant',
  'public': 'Öffentlich',
  'private': 'Privat',
  'draft': 'Entwurf',
  'published': 'Veröffentlicht',
  'archived': 'Archiviert',
  'deleted': 'Gelöscht',
  'restored': 'Wiederhergestellt',
  'backup': 'Sicherung',
  'import': 'Importieren',
  'export': 'Exportieren',
  'sync': 'Synchronisieren',
  'syncing': 'Synchronisierung läuft',
  'synced': 'Synchronisiert',
  'not_synced': 'Nicht synchronisiert',
  'sync_failed': 'Synchronisierung fehlgeschlagen',
  'retry': 'Wiederholen',
  'try_again': 'Erneut versuchen',
  'continue': 'Fortfahren',
  'back': 'Zurück',
  'home': 'Startseite',
  'dashboard': 'Dashboard',
  'overview': 'Übersicht',
  'summary': 'Zusammenfassung',
  'list': 'Liste',
  'grid': 'Raster',
  'table': 'Tabelle',
  'calendar': 'Kalender',
  'map': 'Karte',
  'graph': 'Graph',
  'chart': 'Diagramm',
  'report': 'Bericht',
  'analytics': 'Analytik',
  'insights': 'Einblicke',
  'trends': 'Trends',
  'comparison': 'Vergleich',
  'performance': 'Leistung',
  'growth': 'Wachstum',
  'decline': 'Rückgang',
  'change': 'Änderung',
  'increase': 'Erhöhung',
  'decrease': 'Verringerung',
  'percentage': 'Prozentsatz',
  'value': 'Wert',
  'total': 'Gesamt',
  'subtotal': 'Zwischensumme',
  'average': 'Durchschnitt',
  'median': 'Median',
  'mode': 'Modus',
  'range': 'Bereich',
  'sum': 'Summe',
  'count': 'Anzahl',
  'frequency': 'Häufigkeit',
  'rate': 'Rate',
  'ratio': 'Verhältnis',
  'profit': 'Gewinn',
  'loss': 'Verlust',
  'revenue': 'Umsatz',
  'expense': 'Ausgabe',
  'income': 'Einkommen',
  'cost': 'Kosten',
  'fee': 'Gebühr',
  'tax': 'Steuer',
  'discount': 'Rabatt',
  'commission': 'Provision',
  'interest': 'Zinsen',
  'dividend': 'Dividende',
  'bonus': 'Bonus',
  'reward': 'Belohnung',
  'penalty': 'Strafe',
  'credit': 'Gutschrift',
  'debit': 'Lastschrift',
  'payment': 'Zahlung',
  'refund': 'Rückerstattung',
  'withdrawal': 'Abhebung',
  'transfer': 'Überweisung',
  'exchange': 'Austausch',
  'trade': 'Handel',
  'investment': 'Investition',
  'savings': 'Ersparnisse',
  'account': 'Konto',
  'wallet': 'Geldbörse',
  'card': 'Karte',
  'bank': 'Bank',
  'currency': 'Währung',
  'crypto': 'Krypto',
  'stock': 'Aktie',
  'bond': 'Anleihe',
  'commodity': 'Rohstoff',
  'forex': 'Forex',
  'index': 'Index',
  'etf': 'ETF',
  'mutual_fund': 'Investmentfonds',
  'real_estate': 'Immobilien',
  'option': 'Option',
  'future': 'Future',
  'derivative': 'Derivat',
  'security': 'Wertpapier',
  'instrument': 'Instrument',
  'market': 'Markt',
  'exchange_market': 'Börse',
  'broker': 'Makler',
  'dealer': 'Händler',
  'trader': 'Händler',
  'investor': 'Investor',
  'buyer': 'Käufer',
  'seller': 'Verkäufer',
  'bid': 'Gebot',
  'ask': 'Briefkurs',
  'spread': 'Spread',
  'volume': 'Volumen',
  'liquidity': 'Liquidität',
  'volatility': 'Volatilität',
  'trend': 'Trend',
  'bullish': 'Bullisch',
  'bearish': 'Bärisch',
  'neutral': 'Neutral',
  'support': 'Unterstützung',
  'resistance': 'Widerstand',
  'breakout': 'Ausbruch',
  'breakdown': 'Zusammenbruch',
  'reversal': 'Umkehr',
  'continuation': 'Fortsetzung',
  'pattern': 'Muster',
  'signal': 'Signal',
  'indicator': 'Indikator',
  'oscillator': 'Oszillator',
  'moving_average': 'Gleitender Durchschnitt',
  'rsi': 'RSI',
  'macd': 'MACD',
  'bollinger_bands': 'Bollinger-Bänder',
  'stochastic': 'Stochastik',
  'adx': 'ADX',
  'atr': 'ATR',
  'cci': 'CCI',
  'williams_r': 'Williams %R',
  'momentum': 'Momentum',
  'roc': 'ROC',
  'obv': 'OBV',
  'vwap': 'VWAP',
  'ema': 'EMA',
  'sma': 'SMA',
  'wma': 'WMA',
  'hma': 'HMA',
  'ichimoku': 'Ichimoku',
  'parabolic_sar': 'Parabolic SAR',
  'keltner_channels': 'Keltner-Kanäle',
  'donchian_channels': 'Donchian-Kanäle',
  'envelope': 'Umschlag',
  'alligator': 'Alligator',
  'fractals': 'Fraktale',
  'gator': 'Gator',
  'awesome_oscillator': 'Awesome Oscillator',
  'accelerator': 'Accelerator',
  'market_facilitation': 'Marktfazilitation',
  'zigzag': 'ZigZag',
  'elliott_wave': 'Elliott-Welle',
  'gann': 'Gann',
  'andrews_pitchfork': 'Andrews Pitchfork',
  'trendline': 'Trendlinie',
  'channel': 'Kanal',
  'rectangle': 'Rechteck',
  'triangle': 'Dreieck',
  'wedge': 'Keil',
  'flag': 'Flagge',
  'pennant': 'Wimpel',
  'head_shoulders': 'Kopf und Schultern',
  'double_top': 'Doppel-Top',
  'double_bottom': 'Doppel-Boden',
  'triple_top': 'Triple-Top',
  'triple_bottom': 'Triple-Boden',
  'cup_handle': 'Tasse mit Henkel',
  'rounding_bottom': 'Runder Boden',
  'ascending_triangle': 'Aufsteigendes Dreieck',
  'descending_triangle': 'Absteigendes Dreieck',
  'symmetrical_triangle': 'Symmetrisches Dreieck',
  'rising_wedge': 'Steigender Keil',
  'falling_wedge': 'Fallender Keil',
  'bull_flag': 'Bullen-Flagge',
  'bear_flag': 'Bären-Flagge',
  'bull_pennant': 'Bullen-Wimpel',
  'bear_pennant': 'Bären-Wimpel',
  'gap': 'Lücke',
  'island_reversal': 'Inselumkehr',
  'candlestick': 'Kerze',
  'doji': 'Doji',
  'hammer': 'Hammer',
  'hanging_man': 'Hängender Mann',
  'shooting_star': 'Sternschnuppe',
  'inverted_hammer': 'Umgekehrter Hammer',
  'engulfing': 'Verschlingend',
  'harami': 'Harami',
  'piercing': 'Durchdringend',
  'dark_cloud': 'Dunkle Wolke',
  'morning_star': 'Morgenstern',
  'evening_star': 'Abendstern',
  'three_white_soldiers': 'Drei weiße Soldaten',
  'three_black_crows': 'Drei schwarze Krähen',
  'spinning_top': 'Kreisel',
  'marubozu': 'Marubozu',
  'tweezer': 'Pinzette',
  'abandoned_baby': 'Verlassenes Baby',
  'three_inside': 'Drei innen',
  'three_outside': 'Drei außen',
  'rising_three': 'Steigende Drei',
  'falling_three': 'Fallende Drei',
  'upside_gap': 'Aufwärtslücke',
  'downside_gap': 'Abwärtslücke',
  'kicking': 'Tretend',
  'ladder': 'Leiter',
  'three_line_strike': 'Drei-Linien-Streik',
  'two_crows': 'Zwei Krähen',
  'unique_three_river': 'Einzigartiger Drei-Fluss',
  'concealing_baby_swallow': 'Versteckte Babyschwalbe',
  'stick_sandwich': 'Stock-Sandwich',
  'matching_low': 'Übereinstimmendes Tief',
  'homing_pigeon': 'Brieftaube',
  'ladder_bottom': 'Leiterboden',
  'belt_hold': 'Gürtelgriff',
  'upside_tasuki_gap': 'Aufwärts-Tasuki-Lücke',
  'downside_tasuki_gap': 'Abwärts-Tasuki-Lücke',
  'side_by_side': 'Seite an Seite',
  'separating_lines': 'Trennlinien',
  'in_neck': 'Im Nacken',
  'on_neck': 'Am Nacken',
  'thrusting': 'Stoßend',
  'mat_hold': 'Matten-Halt',
  'breakaway': 'Ausbruch',
  'three_stars_south': 'Drei Sterne im Süden',
  'deliberation': 'Beratung',
  'advance_block': 'Vorschussblock',
  'stalled_pattern': 'Gestautes Muster',
  'doji_star': 'Doji-Stern',
  'dragonfly_doji': 'Libellen-Doji',
  'gravestone_doji': 'Grabstein-Doji',
  'long_legged_doji': 'Langbeiniger Doji',
  'rickshaw_man': 'Rikscha-Mann',
  'high_wave': 'Hohe Welle',
  'counterattack': 'Gegenangriff',
  'meeting_lines': 'Trefflinien',
};