// lib/localization/app_localizations_ko.dart
// Traduções em coreano (com uma chave estranha única para evitar colisões)
// Substitui/ajusta conforme necessário.

const Map<String, String> ko = {
  'flibbertigibbet': 'flibbertigibbet', // mesma palavra estranha aqui
  'login': '로그인',
  'create_account': '계정 만들기',
  'already_have_account': '이미 계정이 있으신가요? 로그인',
  'name': '이름',
  'email': '이메일',
  'password': '비밀번호',
  'birth_date': '생년월일 (YYYY-MM-DD)',
  'phone': '전화번호',
  'enter_name': '이름을 입력하세요',
  'enter_email': '이메일을 입력하세요',
  'invalid_email': '유효하지 않은 이메일 주소',
  'enter_password': '비밀번호를 입력하세요',
  'password_too_short': '비밀번호는 최소 6자 이상이어야 합니다',
  'enter_birth_date': '생년월일을 입력하세요',
  'invalid_date': '유효하지 않은 날짜 형식',
  'enter_phone': '전화번호를 입력하세요',
  'age_restriction': '만 18세 이상이어야 합니다',
  'auth_error': '인증 오류',
  'account_created': '계정이 성공적으로 생성되었습니다',
  'chats': '채팅',
  'hub': '허브',
  'converter': '변환기',
  'news': '뉴스',
  'profile': '프로필',
  'export_data': '사용자 데이터 내보내기',
  'send_data': '데이터 전송',
  'data_sent': '데이터가 성공적으로 전송되었습니다',
  'error_sending_data': '데이터 전송 오류',
  'type_message': '메시지를 입력하세요...',
  'no_messages': '아직 메시지가 없습니다.\n첫 번째로 보내보세요!',
  'error_loading_messages': '메시지 로드 오류',
  'hello': '안녕하세요',
  'portfolio': '포트폴리오',
  'quick_actions': '빠른 작업',
  'send': '보내기',
  'receive': '받기',
  'deposit': '입금',
  'convert': '변환',
  'watchlist': '관심 목록',
  'no_watchlists': '아직 관심 목록이 없습니다',
  'recent_alerts': '최근 알림',
  'no_alerts': '아직 알림이 없습니다',
  'activities': '활동',
  'transactions': '거래',
  'orders': '주문',
  'alerts': '알림',
  'reports': '보고서',
  'no_transactions': '아직 거래가 없습니다',
  'no_orders': '아직 주문이 없습니다',
  'generate_report': '보고서 생성',
  'feed': '피드',
  'create_post': '게시물 작성',
  'write_post': '게시물을 작성하세요...',
  'post': '게시',
  'marketplace': '마켓플레이스',
  'bio': '소개',
  'update_bio': '소개 업데이트',
  'statistics': '통계',
  'points': '포인트',
  'followers': '팔로워',
  'settings': '설정',
  'themes': '테마',
  'languages': '언어',
  'integrations': '통합',
  'security': '보안',
  'logout': '로그아웃',
  'charts': '차트',
  'screener': '스크리너',
  'calculators': '계산기',
  'journal': '저널',
  'strategies': '전략',
  'backtesting': '백테스팅',
  'paper_trading': '모의 거래',
  'reminders': '알림',
  'researcher': '리서처',
  'dictionary': '사전',
  'heatmaps': '히트맵',
  'correlation': '상관관계',
  'football': '축구',
  'entertainment': '엔터테인먼트',
  'learning': '학습',
  'webinars': '웨비나',
  'add_indicator': '지표 추가',
  'filters': '필터',
  'run_screener': '스크리너 실행',
  'results': '결과',
  'position': '포지션',
  'fibonacci': '피보나치',
  'pivot_points': '피벗 포인트',
  'risk_percentage': '위험 비율',
  'stop_loss': '손절매',
  'calculate': '계산',
  'new_entry': '새 항목',
  'add_entry': '항목 추가',
  'select_strategy': '전략 선택',
  'asset': '자산',
  'start_date': '시작일',
  'end_date': '종료일',
  'run_backtest': '백테스트 실행',
  'backtest_results': '백테스트 결과',
  'balance': '잔액',
  'positions': '포지션',
  'place_order': '주문하기',
  'buy': '매수',
  'sell': '매도',
  'quantity': '수량',
  'price': '가격',
  'title': '제목',
  'date': '날짜',
  'add_reminder': '알림 추가',
  'search_query': '검색 쿼리',
  'search': '검색',
  'search_term': '검색어',
  'amount': '금액',
  'result': '결과',
  'select_assets': '자산 선택',
  'calculate_correlation': '상관관계 계산',
  'trading_simulator': '거래 시뮬레이터',
  'score': '점수',
  'start_game': '게임 시작',
  'quiz': '퀴즈',
  'quiz_complete': '퀴즈 완료',
  'movies': '영화',
  'menu': '메뉴',
  'error_loading': '데이터 로드 오류',
  'close': '닫기',
  'send_receive': '송수신',
  'notifications': '알림',
  'performance_chart': '성과 차트',
  'order_book': '주문서',
  'condition': '조건',
  'status': '상태',
  'description': '설명',
  'timestamp': '타임스탬프',
  'type': '유형',
  'active': '활성',
  'triggered': '트리거됨',
  'cancel': '취소',
  'save': '저장',
  'edit': '편집',
  'delete': '삭제',
  'confirm': '확인',
  'success': '성공',
  'error': '오류',
  'warning': '경고',
  'info': '정보',
  'loading': '로딩 중...',
  'no_data': '데이터 없음',
  'refresh': '새로고침',
  'filter': '필터',
  'sort': '정렬',
  'ascending': '오름차순',
  'descending': '내림차순',
  'all': '전체',
  'none': '없음',
  'select': '선택',
  'selected': '선택됨',
  'deselect': '선택 해제',
  'apply': '적용',
  'reset': '재설정',
  'clear': '지우기',
  'done': '완료',
  'next': '다음',
  'previous': '이전',
  'skip': '건너뛰기',
  'finish': '종료',
  'yes': '예',
  'no': '아니오',
  'ok': '확인',
  'got_it': '알겠습니다',
  'learn_more': '자세히 보기',
  'see_all': '전체 보기',
  'show_more': '더 보기',
  'show_less': '간략히',
  'expand': '확장',
  'collapse': '축소',
  'open': '열기',
  'share': '공유',
  'copy': '복사',
  'paste': '붙여넣기',
  'cut': '잘라내기',
  'undo': '실행 취소',
  'redo': '다시 실행',
  'upload': '업로드',
  'download': '다운로드',
  'print': '인쇄',
  'preview': '미리보기',
  'view': '보기',
  'details': '세부정보',
  'more': '더 보기',
  'less': '간략히',
  'help': '도움말',
  'about': '정보',
  'version': '버전',
  'terms': '약관',
  'privacy': '개인정보',
  'contact': '연락처',
  'feedback': '피드백',
  'rate_app': '앱 평가',
  'update': '업데이트',
  'new_version': '새 버전',
  'required': '필수',
  'optional': '선택사항',
  'recommended': '권장',
  'popular': '인기',
  'trending': '트렌딩',
  'new': '새로운',
  'featured': '추천',
  'top': '상위',
  'best': '최고',
  'latest': '최신',
  'recent': '최근',
  'today': '오늘',
  'yesterday': '어제',
  'this_week': '이번 주',
  'this_month': '이번 달',
  'this_year': '올해',
  'last_week': '지난주',
  'last_month': '지난달',
  'last_year': '작년',
  'custom': '사용자 지정',
  'default': '기본값',
  'enabled': '활성화됨',
  'disabled': '비활성화됨',
  'on': '켜짐',
  'off': '꺼짐',
  'automatic': '자동',
  'manual': '수동',
  'always': '항상',
  'never': '안함',
  'ask_question': '묻기', // corrigido
  'light': '라이트',
  'dark': '다크',
  'system': '시스템',
  'high': '높음',
  'medium': '중간',
  'low': '낮음',
  'very_high': '매우 높음',
  'very_low': '매우 낮음',
  'maximum': '최대',
  'minimum': '최소',
  'unlimited': '무제한',
  'limited': '제한됨',
  'free': '무료',
  'premium': '프리미엄',
  'pro': '프로',
  'basic': '기본',
  'standard': '표준',
  'advanced': '고급',
  'beginner': '초급',
  'intermediate': '중급',
  'expert': '전문가',
  'easy': '쉬움',
  'normal': '보통',
  'hard': '어려움',
  'complete': '완료',
  'incomplete': '미완료',
  'pending': '대기 중',
  'approved': '승인됨',
  'rejected': '거부됨',
  'cancelled': '취소됨',
  'failed': '실패',
  'processing': '처리 중',
  'completed': '완료됨',
  'verified': '인증됨',
  'unverified': '미인증',
  'connected': '연결됨',
  'disconnected': '연결 끊김',
  'online': '온라인',
  'offline': '오프라인',
  'available': '사용 가능',
  'unavailable': '사용 불가',
  'in_stock': '재고 있음',
  'out_of_stock': '품절',
  'coming_soon': '곧 출시',
  'maintenance': '유지보수',
  'emergency': '긴급',
  'scheduled': '예정됨',
  'unscheduled': '예정되지 않음',
  'public': '공개',
  'private': '비공개',
  'draft': '초안',
  'published': '게시됨',
  'archived': '보관됨',
  'deleted': '삭제됨',
  'restored': '복원됨',
  'backup': '백업',
  'import': '가져오기',
  'export': '내보내기',
  'sync': '동기화',
  'syncing': '동기화 중',
  'synced': '동기화됨',
  'not_synced': '동기화 안 됨',
  'sync_failed': '동기화 실패',
  'retry': '재시도',
  'try_again': '다시 시도',
  'continue': '계속',
  'back': '뒤로',
  'home': '홈',
  'dashboard': '대시보드',
  'overview': '개요',
  'summary': '요약',
  'list': '목록',
  'grid': '그리드',
  'table': '테이블',
  'calendar': '캘린더',
  'map': '지도',
  'graph': '그래프',
  'chart': '차트',
  'report': '보고서',
  'analytics': '분석',
  'insights': '인사이트',
  'trends': '트렌드',
  'comparison': '비교',
  'performance': '성과',
  'growth': '성장',
  'decline': '하락',
  'change': '변경',
  'increase': '증가',
  'decrease': '감소',
  'percentage': '백분율',
  'value': '값',
  'total': '총계',
  'subtotal': '소계',
  'average': '평균',
  'median': '중앙값',
  'mode': '최빈값',
  'range': '범위',
  'sum': '합계',
  'count': '개수',
  'frequency': '빈도',
  'rate': '비율',
  'ratio': '비율',
  'profit': '수익',
  'loss': '손실',
  'revenue': '매출',
  'expense': '비용',
  'income': '소득',
  'cost': '비용',
  'fee': '수수료',
  'tax': '세금',
  'discount': '할인',
  'commission': '수수료',
  'interest': '이자',
  'dividend': '배당금',
  'bonus': '보너스',
  'reward': '보상',
  'penalty': '벌금',
  'credit': '크레딧',
  'debit': '차변',
  'payment': '결제',
  'refund': '환불',
  'withdrawal': '출금',
  'transfer': '송금',
  'exchange': '환전',
  'trade': '거래',
  'investment': '투자',
  'savings': '저축',
  'account': '계정',
  'wallet': '지갑',
  'card': '카드',
  'bank': '은행',
  'currency': '통화',
  'crypto': '암호화폐',
  'stock': '주식',
  'bond': '채권',
  'commodity': '상품',
  'forex': '외환',
  'index': '지수',
  'etf': 'ETF',
  'mutual_fund': '뮤추얼 펀드',
  'real_estate': '부동산',
  'option': '옵션',
  'future': '선물',
  'derivative': '파생상품',
  'instrument': '금융상품',
  'market': '시장',
  'exchange_market': '거래소',
  'broker': '브로커',
  'dealer': '딜러',
  'trader': '트레이더',
  'investor': '투자자',
  'buyer': '구매자',
  'seller': '판매자',
  'bid': '매수호가',
  'ask': '매도호가',
  'spread': '스프레드',
  'volume': '거래량',
  'liquidity': '유동성',
  'volatility': '변동성',
  'trend': '추세',
  'bullish': '강세',
  'bearish': '약세',
  'neutral': '중립',
  'support': '지지선',
  'resistance': '저항선',
  'breakout': '돌파',
  'breakdown': '붕괴',
  'reversal': '반전',
  'continuation': '지속',
  'pattern': '패턴',
  'signal': '신호',
  'indicator': '지표',
  'oscillator': '오실레이터',
  'moving_average': '이동평균',
  'rsi': 'RSI',
  'macd': 'MACD',
  'bollinger_bands': '볼린저 밴드',
  'stochastic': '스토캐스틱',
  'adx': 'ADX',
  'atr': 'ATR',
  'cci': 'CCI',
  'williams_r': '윌리엄스 %R',
  'momentum': '모멘텀',
  'roc': 'ROC',
  'obv': 'OBV',
  'vwap': 'VWAP',
  'ema': 'EMA',
  'sma': 'SMA',
  'wma': 'WMA',
  'hma': 'HMA',
  'ichimoku': '일목균형표',
  'parabolic_sar': '파라볼릭 SAR',
  'keltner_channels': '켈트너 채널',
  'donchian_channels': '돈치안 채널',
  'envelope': '엔벨로프',
  'alligator': '앨리게이터',
  'fractals': '프랙탈',
  'gator': '게이터',
  'awesome_oscillator': '어썸 오실레이터',
  'accelerator': '가속기',
  'market_facilitation': '시장 촉진',
  'zigzag': '지그재그',
  'elliott_wave': '엘리어트 파동',
  'gann': '갠',
  'andrews_pitchfork': '앤드류스 피치포크',
  'trendline': '추세선',
  'channel': '채널',
  'rectangle': '직사각형',
  'triangle': '삼각형',
  'wedge': '쐐기',
  'flag': '깃발',
  'pennant': '페넌트',
  'head_shoulders': '헤드앤숄더',
  'double_top': '이중 천장',
  'double_bottom': '이중 바닥',
  'triple_top': '삼중 천장',
  'triple_bottom': '삼중 바닥',
  'cup_handle': '컵 앤 핸들',
  'rounding_bottom': '라운딩 바닥',
  'ascending_triangle': '상승 삼각형',
  'descending_triangle': '하락 삼각형',
  'symmetrical_triangle': '대칭 삼각형',
  'rising_wedge': '상승 쐐기',
  'falling_wedge': '하락 쐐기',
  'bull_flag': '강세 깃발',
  'bear_flag': '약세 깃발',
  'bull_pennant': '강세 페넌트',
  'bear_pennant': '약세 페넌트',
  'gap': '갭',
  'island_reversal': '아일랜드 리버설',
  'candlestick': '캔들스틱',
  'doji': '도지',
  'hammer': '해머',
  'hanging_man': '행잉맨',
  'shooting_star': '슈팅스타',
  'inverted_hammer': '역망치',
  'engulfing': '잉걸핑',
  'harami': '하라미',
  'piercing': '관통형',
  'dark_cloud': '먹구름',
  'morning_star': '샛별',
  'evening_star': '저녁별',
  'three_white_soldiers': '세 명의 백기사',
  'three_black_crows': '세 마리의 까마귀',
  'spinning_top': '팽이',
  'marubozu': '마루보즈',
  'tweezer': '족집게',
  'abandoned_baby': '버려진 아기',
  'three_inside': '쓰리 인사이드',
  'three_outside': '쓰리 아웃사이드',
  'rising_three': '상승 삼법',
  'falling_three': '하락 삼법',
  'upside_gap': '상승 갭',
  'downside_gap': '하락 갭',
  'kicking': '키킹',
  'ladder': '래더',
  'three_line_strike': '삼선타격',
  'two_crows': '두 마리 까마귀',
  'unique_three_river': '특이한 삼천',
  'concealing_baby_swallow': '숨긴 제비',
  'stick_sandwich': '스틱 샌드위치',
  'matching_low': '매칭 로우',
  'homing_pigeon': '귀환 비둘기',
  'ladder_bottom': '래더 바닥',
  'belt_hold': '벨트 홀드',
  'upside_tasuki_gap': '상승 타스키 갭',
  'downside_tasuki_gap': '하락 타스키 갭',
  'side_by_side': '나란히',
  'separating_lines': '분리선',
  'in_neck': '인 넥',
  'on_neck': '온 넥',
  'thrusting': '밀어내기',
  'mat_hold': '매트 홀드',
  'breakaway': '브레이크어웨이',
  'three_stars_south': '남쪽의 세 별',
  'deliberation': '숙고',
  'advance_block': '어드밴스 블록',
  'stalled_pattern': '정체 패턴',
  'doji_star': '도지 스타',
  'dragonfly_doji': '잠자리 도지',
  'gravestone_doji': '묘비 도지',
  'long_legged_doji': '긴 다리 도지',
  'rickshaw_man': '인력거꾼',
  'high_wave': '하이 웨이브',
  'counterattack': '역습',
  'meeting_lines': '만나는 선',
};