const Map<String, String> es = {
  'login': 'Iniciar sesión',
  'create_account': 'Crear cuenta',
  'already_have_account': '¿Ya tienes una cuenta? Inicia sesión',
  'name': 'Nombre',
  'email': 'Correo electrónico',
  'password': 'Contraseña',
  'birth_date': 'Fecha de nacimiento (AAAA-MM-DD)',
  'phone': 'Número de teléfono',
  'enter_name': 'Por favor ingrese su nombre',
  'enter_email': 'Por favor ingrese su correo electrónico',
  'invalid_email': 'Dirección de correo electrónico inválida',
  'enter_password': 'Por favor ingrese su contraseña',
  'password_too_short': 'La contraseña debe tener al menos 6 caracteres',
  'enter_birth_date': 'Por favor ingrese su fecha de nacimiento',
  'invalid_date': 'Formato de fecha inválido',
  'enter_phone': 'Por favor ingrese su número de teléfono',
  'age_restriction': 'Debe tener al menos 18 años',
  'auth_error': 'Error de autenticación',
  'account_created': 'Cuenta creada exitosamente',
  'chats': 'Chats',
  'hub': 'Hub',
  'converter': 'Convertidor',
  'news': 'Noticias',
  'profile': 'Perfil',
  'export_data': 'Exportar datos de usuario',
  'send_data': 'Enviar datos',
  'data_sent': 'Datos enviados exitosamente',
  'error_sending_data': 'Error al enviar datos',
  'type_message': 'Escribe tu mensaje...',
  'no_messages': 'Aún no hay mensajes.\n¡Sé el primero en enviar!',
  'error_loading_messages': 'Error al cargar mensajes',
  'hello': 'Hola',
  'portfolio': 'Portafolio',
  'quick_actions': 'Acciones rápidas',
  'send': 'Enviar',
  'receive': 'Recibir',
  'deposit': 'Depósito',
  'convert': 'Convertir',
  'watchlist': 'Lista de seguimiento',
  'no_watchlists': 'Aún no hay listas de seguimiento',
  'recent_alerts': 'Alertas recientes',
  'no_alerts': 'Aún no hay alertas',
  'activities': 'Actividades',
  'transactions': 'Transacciones',
  'orders': 'Órdenes',
  'alerts': 'Alertas',
  'reports': 'Informes',
  'no_transactions': 'Aún no hay transacciones',
  'no_orders': 'Aún no hay órdenes',
  'generate_report': 'Generar informe',
  'feed': 'Feed',
  'create_post': 'Crear publicación',
  'write_post': 'Escribe tu publicación...',
  'post': 'Publicación',
  'marketplace': 'Mercado',
  'bio': 'Biografía',
  'update_bio': 'Actualizar biografía',
  'statistics': 'Estadísticas',
  'points': 'Puntos',
  'followers': 'Seguidores',
  'settings': 'Configuración',
  'themes': 'Temas',
  'languages': 'Idiomas',
  'integrations': 'Integraciones',
  'security': 'Seguridad',
  'logout': 'Cerrar sesión',
  'charts': 'Gráficos',
  'screener': 'Screener',
  'calculators': 'Calculadoras',
  'journal': 'Diario',
  'strategies': 'Estrategias',
  'backtesting': 'Backtesting',
  'paper_trading': 'Trading de papel',
  'reminders': 'Recordatorios',
  'researcher': 'Investigador',
  'dictionary': 'Diccionario',
  'heatmaps': 'Mapas de calor',
  'correlation': 'Correlación',
  'football': 'Fútbol',
  'entertainment': 'Entretenimiento',
  'learning': 'Aprendizaje',
  'webinars': 'Webinarios',
  'add_indicator': 'Agregar indicador',
  'filters': 'Filtros',
  'run_screener': 'Ejecutar screener',
  'results': 'Resultados',
  'position': 'Posición',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Puntos pivote',
  'risk_percentage': 'Porcentaje de riesgo',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calcular',
  'new_entry': 'Nueva entrada',
  'add_entry': 'Agregar entrada',
  'select_strategy': 'Seleccionar estrategia',
  'asset': 'Activo',
  'start_date': 'Fecha de inicio',
  'end_date': 'Fecha de fin',
  'run_backtest': 'Ejecutar backtest',
  'backtest_results': 'Resultados del backtest',
  'balance': 'Balance',
  'positions': 'Posiciones',
  'place_order': 'Colocar orden',
  'buy': 'Comprar',
  'sell': 'Vender',
  'quantity': 'Cantidad',
  'price': 'Precio',
  'title': 'Título',
  'date': 'Fecha',
  'add_reminder': 'Agregar recordatorio',
  'search_query': 'Consulta de búsqueda',
  'search': 'Buscar',
  'search_term': 'Término de búsqueda',
  'amount': 'Cantidad',
  'result': 'Resultado',
  'select_assets': 'Seleccionar activos',
  'calculate_correlation': 'Calcular correlación',
  'trading_simulator': 'Simulador de trading',
  'score': 'Puntuación',
  'start_game': 'Iniciar juego',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz completado',
  'movies': 'Películas',
  'menu': 'Menú',
  'error_loading': 'Error al cargar datos',
  'close': 'Cerrar',
  'send_receive': 'Enviar/Recibir',
  'notifications': 'Notificaciones',
  'performance_chart': 'Gráfico de rendimiento',
  'order_book': 'Libro de órdenes',
  'condition': 'Condición',
  'status': 'Estado',
  'description': 'Descripción',
  'timestamp': 'Marca de tiempo',
  'type': 'Tipo',
  'active': 'Activo',
  'triggered': 'Activado',
  'cancel': 'Cancelar',
  'save': 'Guardar',
  'edit': 'Editar',
  'delete': 'Eliminar',
  'confirm': 'Confirmar',
  'success': 'Éxito',
  'error': 'Error',
  'warning': 'Advertencia',
  'info': 'Información',
  'loading': 'Cargando...',
  'no_data': 'No hay datos disponibles',
  'refresh': 'Actualizar',
  'filter': 'Filtrar',
  'sort': 'Ordenar',
  'ascending': 'Ascendente',
  'descending': 'Descendente',
  'all': 'Todos',
  'none': 'Ninguno',
  'select': 'Seleccionar',
  'selected': 'Seleccionado',
  'deselect': 'Deseleccionar',
  'apply': 'Aplicar',
  'reset': 'Restablecer',
  'clear': 'Limpiar',
  'done': 'Hecho',
  'next': 'Siguiente',
  'previous': 'Anterior',
  'skip': 'Omitir',
  'finish': 'Finalizar',
  'yes': 'Sí',
  'no': 'No',
  'ok': 'OK',
  'got_it': 'Entendido',
  'learn_more': 'Aprender más',
  'see_all': 'Ver todo',
  'show_more': 'Mostrar más',
  'show_less': 'Mostrar menos',
  'expand': 'Expandir',
  'collapse': 'Colapsar',
  'open': 'Abrir',
  'share': 'Compartir',
  'copy': 'Copiar',
  'paste': 'Pegar',
  'cut': 'Cortar',
  'undo': 'Deshacer',
  'redo': 'Rehacer',
  'upload': 'Subir',
  'download': 'Descargar',
  'print': 'Imprimir',
  'preview': 'Vista previa',
  'view': 'Ver',
  'details': 'Detalles',
  'more': 'Más',
  'less': 'Menos',
  'help': 'Ayuda',
  'about': 'Acerca de',
  'version': 'Versión',
  'terms': 'Términos',
  'privacy': 'Privacidad',
  'contact': 'Contacto',
  'feedback': 'Comentarios',
  'rate_app': 'Calificar app',
  'update': 'Actualizar',
  'new_version': 'Nueva versión',
  'required': 'Requerido',
  'optional': 'Opcional',
  'recommended': 'Recomendado',
  'popular': 'Popular',
  'trending': 'Tendencia',
  'new': 'Nuevo',
  'featured': 'Destacado',
  'top': 'Top',
  'best': 'Mejor',
  'latest': 'Último',
  'recent': 'Reciente',
  'today': 'Hoy',
  'yesterday': 'Ayer',
  'this_week': 'Esta semana',
  'this_month': 'Este mes',
  'this_year': 'Este año',
  'last_week': 'Semana pasada',
  'last_month': 'Mes pasado',
  'last_year': 'Año pasado',
  'custom': 'Personalizado',
  'default': 'Predeterminado',
  'enabled': 'Habilitado',
  'disabled': 'Deshabilitado',
  'on': 'Encendido',
  'off': 'Apagado',
  'automatic': 'Automático',
  'manual': 'Manual',
  'always': 'Siempre',
  'never': 'Nunca',
  'ask': 'Preguntar',
  'light': 'Claro',
  'dark': 'Oscuro',
  'system': 'Sistema',
  'high': 'Alto',
  'medium': 'Medio',
  'low': 'Bajo',
  'very_high': 'Muy alto',
  'very_low': 'Muy bajo',
  'maximum': 'Máximo',
  'minimum': 'Mínimo',
  'unlimited': 'Ilimitado',
  'limited': 'Limitado',
  'free': 'Gratis',
  'premium': 'Premium',
  'pro': 'Pro',
  'basic': 'Básico',
  'standard': 'Estándar',
  'advanced': 'Avanzado',
  'beginner': 'Principiante',
  'intermediate': 'Intermedio',
  'expert': 'Experto',
  'easy': 'Fácil',
  'normal': 'Normal',
  'hard': 'Difícil',
  'complete': 'Completo',
  'incomplete': 'Incompleto',
  'pending': 'Pendiente',
  'approved': 'Aprobado',
  'rejected': 'Rechazado',
  'cancelled': 'Cancelado',
  'failed': 'Fallido',
  'processing': 'Procesando',
  'completed': 'Completado',
  'verified': 'Verificado',
  'unverified': 'No verificado',
  'connected': 'Conectado',
  'disconnected': 'Desconectado',
  'online': 'En línea',
  'offline': 'Fuera de línea',
  'available': 'Disponible',
  'unavailable': 'No disponible',
  'in_stock': 'En stock',
  'out_of_stock': 'Agotado',
  'coming_soon': 'Próximamente',
  'maintenance': 'Mantenimiento',
  'emergency': 'Emergencia',
  'scheduled': 'Programado',
  'unscheduled': 'No programado',
  'public': 'Público',
  'private': 'Privado',
  'draft': 'Borrador',
  'published': 'Publicado',
  'archived': 'Archivado',
  'deleted': 'Eliminado',
  'restored': 'Restaurado',
  'backup': 'Copia de seguridad',
  'import': 'Importar',
  'export': 'Exportar',
  'sync': 'Sincronizar',
  'syncing': 'Sincronizando',
  'synced': 'Sincronizado',
  'not_synced': 'No sincronizado',
  'sync_failed': 'Sincronización fallida',
  'retry': 'Reintentar',
  'try_again': 'Intentar de nuevo',
  'continue': 'Continuar',
  'back': 'Atrás',
  'home': 'Inicio',
  'dashboard': 'Panel',
  'overview': 'Resumen',
  'summary': 'Resumen',
  'list': 'Lista',
  'grid': 'Cuadrícula',
  'table': 'Tabla',
  'calendar': 'Calendario',
  'map': 'Mapa',
  'graph': 'Gráfico',
  'chart': 'Gráfico',
  'report': 'Informe',
  'analytics': 'Análisis',
  'insights': 'Perspectivas',
  'trends': 'Tendencias',
  'comparison': 'Comparación',
  'performance': 'Rendimiento',
  'growth': 'Crecimiento',
  'decline': 'Declive',
  'change': 'Cambio',
  'increase': 'Aumento',
  'decrease': 'Disminución',
  'percentage': 'Porcentaje',
  'value': 'Valor',
  'total': 'Total',
  'subtotal': 'Subtotal',
  'average': 'Promedio',
  'median': 'Mediana',
  'mode': 'Moda',
  'range': 'Rango',
  'sum': 'Suma',
  'count': 'Conteo',
  'frequency': 'Frecuencia',
  'rate': 'Tasa',
  'ratio': 'Proporción',
  'profit': 'Ganancia',
  'loss': 'Pérdida',
  'revenue': 'Ingresos',
  'expense': 'Gasto',
  'income': 'Ingreso',
  'cost': 'Costo',
  'fee': 'Tarifa',
  'tax': 'Impuesto',
  'discount': 'Descuento',
  'commission': 'Comisión',
  'interest': 'Interés',
  'dividend': 'Dividendo',
  'bonus': 'Bonificación',
  'reward': 'Recompensa',
  'penalty': 'Penalización',
  'credit': 'Crédito',
  'debit': 'Débito',
  'payment': 'Pago',
  'refund': 'Reembolso',
  'withdrawal': 'Retiro',
  'transfer': 'Transferencia',
  'exchange': 'Intercambio',
  'trade': 'Comercio',
  'investment': 'Inversión',
  'savings': 'Ahorros',
  'account': 'Cuenta',
  'wallet': 'Cartera',
  'card': 'Tarjeta',
  'bank': 'Banco',
  'currency': 'Moneda',
  'crypto': 'Cripto',
  'stock': 'Acción',
  'bond': 'Bono',
  'commodity': 'Materia prima',
  'forex': 'Forex',
  'index': 'Índice',
  'etf': 'ETF',
  'mutual_fund': 'Fondo mutuo',
  'real_estate': 'Bienes raíces',
  'option': 'Opción',
  'future': 'Futuro',
  'derivative': 'Derivado',
  'security': 'Valor',
  'instrument': 'Instrumento',
  'market': 'Mercado',
  'exchange_market': 'Bolsa',
  'broker': 'Corredor',
  'dealer': 'Distribuidor',
  'trader': 'Comerciante',
  'investor': 'Inversor',
  'buyer': 'Comprador',
  'seller': 'Vendedor',
  'bid': 'Oferta',
  'ask': 'Demanda',
  'spread': 'Diferencial',
  'volume': 'Volumen',
  'liquidity': 'Liquidez',
  'volatility': 'Volatilidad',
  'trend': 'Tendencia',
  'bullish': 'Alcista',
  'bearish': 'Bajista',
  'neutral': 'Neutral',
  'support': 'Soporte',
  'resistance': 'Resistencia',
  'breakout': 'Ruptura',
  'breakdown': 'Colapso',
  'reversal': 'Reversión',
  'continuation': 'Continuación',
  'pattern': 'Patrón',
  'signal': 'Señal',
  'indicator': 'Indicador',
  'oscillator': 'Oscilador',
  'moving_average': 'Media móvil',
  'rsi': 'RSI',
  'macd': 'MACD',
  'bollinger_bands': 'Bandas de Bollinger',
  'stochastic': 'Estocástico',
  'adx': 'ADX',
  'atr': 'ATR',
  'cci': 'CCI',
  'williams_r': 'Williams %R',
  'momentum': 'Momentum',
  'roc': 'ROC',
  'obv': 'OBV',
  'vwap': 'VWAP',
  'ema': 'EMA',
  'sma': 'SMA',
  'wma': 'WMA',
  'hma': 'HMA',
  'ichimoku': 'Ichimoku',
  'parabolic_sar': 'SAR Parabólico',
  'keltner_channels': 'Canales de Keltner',
  'donchian_channels': 'Canales de Donchian',
  'envelope': 'Envolvente',
  'alligator': 'Caimán',
  'fractals': 'Fractales',
  'gator': 'Gator',
  'awesome_oscillator': 'Oscilador Awesome',
  'accelerator': 'Acelerador',
  'market_facilitation': 'Facilitación del mercado',
  'zigzag': 'ZigZag',
  'elliott_wave': 'Onda de Elliott',
  'gann': 'Gann',
  'andrews_pitchfork': 'Horquilla de Andrews',
  'trendline': 'Línea de tendencia',
  'channel': 'Canal',
  'rectangle': 'Rectángulo',
  'triangle': 'Triángulo',
  'wedge': 'Cuña',
  'flag': 'Bandera',
  'pennant': 'Banderín',
  'head_shoulders': 'Cabeza y hombros',
  'double_top': 'Doble techo',
  'double_bottom': 'Doble suelo',
  'triple_top': 'Triple techo',
  'triple_bottom': 'Triple suelo',
  'cup_handle': 'Taza con asa',
  'rounding_bottom': 'Fondo redondeado',
  'ascending_triangle': 'Triángulo ascendente',
  'descending_triangle': 'Triángulo descendente',
  'symmetrical_triangle': 'Triángulo simétrico',
  'rising_wedge': 'Cuña ascendente',
  'falling_wedge': 'Cuña descendente',
  'bull_flag': 'Bandera alcista',
  'bear_flag': 'Bandera bajista',
  'bull_pennant': 'Banderín alcista',
  'bear_pennant': 'Banderín bajista',
  'gap': 'Brecha',
  'island_reversal': 'Reversión de isla',
  'candlestick': 'Vela',
  'doji': 'Doji',
  'hammer': 'Martillo',
  'hanging_man': 'Hombre colgado',
  'shooting_star': 'Estrella fugaz',
  'inverted_hammer': 'Martillo invertido',
  'engulfing': 'Envolvente',
  'harami': 'Harami',
  'piercing': 'Perforante',
  'dark_cloud': 'Nube oscura',
  'morning_star': 'Estrella de la mañana',
  'evening_star': 'Estrella de la tarde',
  'three_white_soldiers': 'Tres soldados blancos',
  'three_black_crows': 'Tres cuervos negros',
  'spinning_top': 'Peonza',
  'marubozu': 'Marubozu',
  'tweezer': 'Pinza',
  'abandoned_baby': 'Bebé abandonado',
  'three_inside': 'Tres dentro',
  'three_outside': 'Tres fuera',
  'rising_three': 'Tres ascendentes',
  'falling_three': 'Tres descendentes',
  'upside_gap': 'Brecha alcista',
  'downside_gap': 'Brecha bajista',
  'kicking': 'Patada',
  'ladder': 'Escalera',
  'three_line_strike': 'Golpe de tres líneas',
  'two_crows': 'Dos cuervos',
  'unique_three_river': 'Tres ríos únicos',
  'concealing_baby_swallow': 'Golondrina bebé oculta',
  'stick_sandwich': 'Sándwich de palo',
  'matching_low': 'Mínimo coincidente',
  'homing_pigeon': 'Paloma mensajera',
  'ladder_bottom': 'Fondo de escalera',
  'belt_hold': 'Agarre de cinturón',
  'upside_tasuki_gap': 'Brecha Tasuki alcista',
  'downside_tasuki_gap': 'Brecha Tasuki bajista',
  'side_by_side': 'Lado a lado',
  'separating_lines': 'Líneas separadoras',
  'in_neck': 'En el cuello',
  'on_neck': 'En el cuello',
  'thrusting': 'Empujando',
  'mat_hold': 'Sostén de tapete',
  'breakaway': 'Ruptura',
  'three_stars_south': 'Tres estrellas del sur',
  'deliberation': 'Deliberación',
  'advance_block': 'Bloque de avance',
  'stalled_pattern': 'Patrón estancado',
  'doji_star': 'Estrella Doji',
  'dragonfly_doji': 'Doji libélula',
  'gravestone_doji': 'Doji lápida',
  'long_legged_doji': 'Doji de piernas largas',
  'rickshaw_man': 'Hombre rickshaw',
  'high_wave': 'Ola alta',
  'counterattack': 'Contraataque',
  'meeting_lines': 'Líneas de encuentro',
};