const Map<String, String> it = {
  'login': 'Accedi',
  'create_account': 'Crea account',
  'already_have_account': 'Hai già un account? Accedi',
  'name': 'Nome',
  'email': 'Email',
  'password': 'Password',
  'birth_date': 'Data di nascita (AAAA-MM-GG)',
  'phone': 'Numero di telefono',
  'enter_name': 'Inserisci il tuo nome',
  'enter_email': 'Inserisci la tua email',
  'invalid_email': 'Indirizzo email non valido',
  'enter_password': 'Inserisci la tua password',
  'password_too_short': 'La password deve contenere almeno 6 caratteri',
  'enter_birth_date': 'Inserisci la tua data di nascita',
  'invalid_date': 'Formato data non valido',
  'enter_phone': 'Inserisci il tuo numero di telefono',
  'age_restriction': 'Devi avere almeno 18 anni',
  'auth_error': 'Errore di autenticazione',
  'account_created': 'Account creato con successo',
  'chats': 'Chat',
  'hub': 'Hub',
  'converter': 'Convertitore',
  'news': 'Notizie',
  'profile': 'Profilo',
  'export_data': 'Esporta dati utente',
  'send_data': 'Invia dati',
  'data_sent': 'Dati inviati con successo',
  'error_sending_data': 'Errore nell\'invio dei dati',
  'type_message': 'Scrivi il tuo messaggio...',
  'no_messages': 'Nessun messaggio ancora.\nSii il primo a inviare!',
  'error_loading_messages': 'Errore nel caricamento dei messaggi',
  'hello': 'Ciao',
  'portfolio': 'Portafoglio',
  'quick_actions': 'Azioni rapide',
  'send': 'Invia',
  'receive': 'Ricevi',
  'deposit': 'Deposito',
  'convert': 'Converti',
  'watchlist': 'Lista di osservazione',
  'no_watchlists': 'Nessuna lista di osservazione ancora',
  'recent_alerts': 'Avvisi recenti',
  'no_alerts': 'Nessun avviso ancora',
  'activities': 'Attività',
  'transactions': 'Transazioni',
  'orders': 'Ordini',
  'alerts': 'Avvisi',
  'reports': 'Rapporti',
  'no_transactions': 'Nessuna transazione ancora',
  'no_orders': 'Nessun ordine ancora',
  'generate_report': 'Genera rapporto',
  'feed': 'Feed',
  'create_post': 'Crea post',
  'write_post': 'Scrivi il tuo post...',
  'post': 'Post',
  'marketplace': 'Mercato',
  'bio': 'Biografia',
  'update_bio': 'Aggiorna biografia',
  'statistics': 'Statistiche',
  'points': 'Punti',
  'followers': 'Follower',
  'settings': 'Impostazioni',
  'themes': 'Temi',
  'languages': 'Lingue',
  'integrations': 'Integrazioni',
  'security': 'Sicurezza',
  'logout': 'Disconnetti',
  'charts': 'Grafici',
  'screener': 'Screener',
  'calculators': 'Calcolatrici',
  'journal': 'Diario',
  'strategies': 'Strategie',
  'backtesting': 'Backtesting',
  'paper_trading': 'Trading cartaceo',
  'reminders': 'Promemoria',
  'researcher': 'Ricercatore',
  'dictionary': 'Dizionario',
  'heatmaps': 'Mappe di calore',
  'correlation': 'Correlazione',
  'football': 'Calcio',
  'entertainment': 'Intrattenimento',
  'learning': 'Apprendimento',
  'webinars': 'Webinar',
  'add_indicator': 'Aggiungi indicatore',
  'filters': 'Filtri',
  'run_screener': 'Esegui screener',
  'results': 'Risultati',
  'position': 'Posizione',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Punti pivot',
  'risk_percentage': 'Percentuale di rischio',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calcola',
  'new_entry': 'Nuova voce',
  'add_entry': 'Aggiungi voce',
  'select_strategy': 'Seleziona strategia',
  'asset': 'Asset',
  'start_date': 'Data inizio',
  'end_date': 'Data fine',
  'run_backtest': 'Esegui backtest',
  'backtest_results': 'Risultati backtest',
  'balance': 'Saldo',
  'positions': 'Posizioni',
  'place_order': 'Inserisci ordine',
  'buy': 'Acquista',
  'sell': 'Vendi',
  'quantity': 'Quantità',
  'price': 'Prezzo',
  'title': 'Titolo',
  'date': 'Data',
  'add_reminder': 'Aggiungi promemoria',
  'search_query': 'Query di ricerca',
  'search': 'Cerca',
  'search_term': 'Termine di ricerca',
  'amount': 'Importo',
  'result': 'Risultato',
  'select_assets': 'Seleziona asset',
  'calculate_correlation': 'Calcola correlazione',
  'trading_simulator': 'Simulatore di trading',
  'score': 'Punteggio',
  'start_game': 'Inizia gioco',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz completato',
  'movies': 'Film',
  'menu': 'Menu',
  'error_loading': 'Errore nel caricamento dei dati',
  'close': 'Chiudi',
  'send_receive': 'Invia/Ricevi',
  'notifications': 'Notifiche',
  'performance_chart': 'Grafico prestazioni',
  'order_book': 'Libro ordini',
  'condition': 'Condizione',
  'status': 'Stato',
  'description': 'Descrizione',
  'timestamp': 'Timestamp',
  'type': 'Tipo',
  'active': 'Attivo',
  'triggered': 'Attivato',
  'cancel': 'Annulla',
  'save': 'Salva',
  'edit': 'Modifica',
  'delete': 'Elimina',
  'confirm': 'Conferma',
  'success': 'Successo',
  'error': 'Errore',
  'warning': 'Avviso',
  'info': 'Informazione',
  'loading': 'Caricamento...',
  'no_data': 'Nessun dato disponibile',
  'refresh': 'Aggiorna',
  'filter': 'Filtra',
  'sort': 'Ordina',
  'ascending': 'Crescente',
  'descending': 'Decrescente',
  'all': 'Tutto',
  'none': 'Nessuno',
  'select': 'Seleziona',
  'selected': 'Selezionato',
  'deselect': 'Deseleziona',
  'apply': 'Applica',
  'reset': 'Reimposta',
  'clear': 'Cancella',
  'done': 'Fatto',
  'next': 'Avanti',
  'previous': 'Precedente',
  'skip': 'Salta',
  'finish': 'Termina',
  'yes': 'Sì',
  'no': 'No',
  'ok': 'OK',
  'got_it': 'Capito',
  'learn_more': 'Scopri di più',
  'see_all': 'Vedi tutto',
  'show_more': 'Mostra di più',
  'show_less': 'Mostra meno',
  'expand': 'Espandi',
  'collapse': 'Comprimi',
  'open': 'Apri',
  'share': 'Condividi',
  'copy': 'Copia',
  'paste': 'Incolla',
  'cut': 'Taglia',
  'undo': 'Annulla',
  'redo': 'Ripeti',
  'upload': 'Carica',
  'download': 'Scarica',
  'print': 'Stampa',
  'preview': 'Anteprima',
  'view': 'Visualizza',
  'details': 'Dettagli',
  'more': 'Altro',
  'less': 'Meno',
  'help': 'Aiuto',
  'about': 'Informazioni',
  'version': 'Versione',
  'terms': 'Termini',
  'privacy': 'Privacy',
  'contact': 'Contatto',
  'support': 'Supporto',
  'feedback': 'Feedback',
  'rate_app': 'Valuta app',
  'update': 'Aggiorna',
  'new_version': 'Nuova versione',
  'required': 'Richiesto',
  'optional': 'Opzionale',
  'recommended': 'Consigliato',
  'popular': 'Popolare',
  'trending': 'Tendenza',
  'new': 'Nuovo',
  'featured': 'In evidenza',
  'top': 'Top',
  'best': 'Migliore',
  'latest': 'Ultimo',
  'recent': 'Recente',
  'today': 'Oggi',
  'yesterday': 'Ieri',
  'this_week': 'Questa settimana',
  'this_month': 'Questo mese',
  'this_year': 'Quest\'anno',
  'last_week': 'Settimana scorsa',
  'last_month': 'Mese scorso',
  'last_year': 'Anno scorso',
  'custom': 'Personalizzato',
  'default': 'Predefinito',
  'enabled': 'Abilitato',
  'disabled': 'Disabilitato',
  'on': 'Acceso',
  'off': 'Spento',
  'automatic': 'Automatico',
  'manual': 'Manuale',
  'always': 'Sempre',
  'never': 'Mai',
  'ask': 'Chiedi',
  'light': 'Chiaro',
  'dark': 'Scuro',
  'system': 'Sistema',
  'high': 'Alto',
  'medium': 'Medio',
  'low': 'Basso',
  'very_high': 'Molto alto',
  'very_low': 'Molto basso',
  'maximum': 'Massimo',
  'minimum': 'Minimo',
  'unlimited': 'Illimitato',
  'limited': 'Limitato',
  'free': 'Gratuito',
  'premium': 'Premium',
  'pro': 'Pro',
  'basic': 'Base',
  'standard': 'Standard',
  'advanced': 'Avanzato',
  'beginner': 'Principiante',
  'intermediate': 'Intermedio',
  'expert': 'Esperto',
  'easy': 'Facile',
  'normal': 'Normale',
  'hard': 'Difficile',
  'complete': 'Completo',
  'incomplete': 'Incompleto',
  'pending': 'In attesa',
  'approved': 'Approvato',
  'rejected': 'Rifiutato',
  'cancelled': 'Annullato',
  'failed': 'Fallito',
  'processing': 'Elaborazione',
  'completed': 'Completato',
  'verified': 'Verificato',
  'unverified': 'Non verificato',
  'connected': 'Connesso',
  'disconnected': 'Disconnesso',
  'online': 'Online',
  'offline': 'Offline',
  'available': 'Disponibile',
  'unavailable': 'Non disponibile',
  'in_stock': 'Disponibile',
  'out_of_stock': 'Esaurito',
  'coming_soon': 'Prossimamente',
  'maintenance': 'Manutenzione',
  'emergency': 'Emergenza',
  'scheduled': 'Programmato',
  'unscheduled': 'Non programmato',
  'public': 'Pubblico',
  'private': 'Privato',
  'draft': 'Bozza',
  'published': 'Pubblicato',
  'archived': 'Archiviato',
  'deleted': 'Eliminato',
  'restored': 'Ripristinato',
  'backup': 'Backup',
  'import': 'Importa',
  'export': 'Esporta',
  'sync': 'Sincronizza',
  'syncing': 'Sincronizzazione',
  'synced': 'Sincronizzato',
  'not_synced': 'Non sincronizzato',
  'sync_failed': 'Sincronizzazione fallita',
  'retry': 'Riprova',
  'try_again': 'Riprova',
  'continue': 'Continua',
  'back': 'Indietro',
  'home': 'Home',
  'dashboard': 'Dashboard',
  'overview': 'Panoramica',
  'summary': 'Riepilogo',
  'list': 'Lista',
  'grid': 'Griglia',
  'table': 'Tabella',
  'calendar': 'Calendario',
  'map': 'Mappa',
  'graph': 'Grafico',
  'chart': 'Grafico',
  'report': 'Rapporto',
  'analytics': 'Analisi',
  'insights': 'Approfondimenti',
  'trends': 'Tendenze',
  'comparison': 'Confronto',
  'performance': 'Prestazioni',
  'growth': 'Crescita',
  'decline': 'Declino',
  'change': 'Cambiamento',
  'increase': 'Aumento',
  'decrease': 'Diminuzione',
  'percentage': 'Percentuale',
  'value': 'Valore',
  'total': 'Totale',
  'subtotal': 'Subtotale',
  'average': 'Media',
  'median': 'Mediana',
  'mode': 'Moda',
  'range': 'Intervallo',
  'sum': 'Somma',
  'count': 'Conteggio',
  'frequency': 'Frequenza',
  'rate': 'Tasso',
  'ratio': 'Rapporto',
  'profit': 'Profitto',
  'loss': 'Perdita',
  'revenue': 'Ricavi',
  'expense': 'Spesa',
  'income': 'Reddito',
  'cost': 'Costo',
  'fee': 'Commissione',
  'tax': 'Tassa',
  'discount': 'Sconto',
  'commission': 'Commissione',
  'interest': 'Interesse',
  'dividend': 'Dividendo',
  'bonus': 'Bonus',
  'reward': 'Ricompensa',
  'penalty': 'Penalità',
  'credit': 'Credito',
  'debit': 'Debito',
  'payment': 'Pagamento',
  'refund': 'Rimborso',
  'withdrawal': 'Prelievo',
  'transfer': 'Trasferimento',
  'exchange': 'Scambio',
  'trade': 'Commercio',
  'investment': 'Investimento',
  'savings': 'Risparmi',
  'account': 'Account',
  'wallet': 'Portafoglio',
  'card': 'Carta',
  'bank': 'Banca',
  'currency': 'Valuta',
  'crypto': 'Crypto',
  'stock': 'Azione',
  'bond': 'Obbligazione',
  'commodity': 'Materia prima',
  'forex': 'Forex',
  'index': 'Indice',
  'etf': 'ETF',
  'mutual_fund': 'Fondo comune',
  'real_estate': 'Immobiliare',
  'option': 'Opzione',
  'future': 'Future',
  'derivative': 'Derivato',
  'security': 'Titolo',
  'instrument': 'Strumento',
  'market': 'Mercato',
  'exchange_market': 'Borsa',
  'broker': 'Broker',
  'dealer': 'Dealer',
  'trader': 'Trader',
  'investor': 'Investitore',
  'buyer': 'Acquirente',
  'seller': 'Venditore',
  'bid': 'Offerta',
  'ask': 'Richiesta',
  'spread': 'Spread',
  'volume': 'Volume',
  'liquidity': 'Liquidità',
  'volatility': 'Volatilità',
  'trend': 'Tendenza',
  'bullish': 'Rialzista',
  'bearish': 'Ribassista',
  'neutral': 'Neutrale',
  'support': 'Supporto',
  'resistance': 'Resistenza',
  'breakout': 'Rottura',
  'breakdown': 'Crollo',
  'reversal': 'Inversione',
  'continuation': 'Continuazione',
  'pattern': 'Pattern',
  'signal': 'Segnale',
  'indicator': 'Indicatore',
  'oscillator': 'Oscillatore',
  'moving_average': 'Media mobile',
  'rsi': 'RSI',
  'macd': 'MACD',
  'bollinger_bands': 'Bande di Bollinger',
  'stochastic': 'Stocastico',
  'adx': 'ADX',
  'atr': 'ATR',
  'cci': 'CCI',
  'williams_r': 'Williams %R',
  'momentum': 'Momentum',
  'roc': 'ROC',
  'obv': 'OBV',
  'vwap': 'VWAP',
  'ema': 'EMA',
  'sma': 'SMA',
  'wma': 'WMA',
  'hma': 'HMA',
  'ichimoku': 'Ichimoku',
  'parabolic_sar': 'SAR Parabolico',
  'keltner_channels': 'Canali di Keltner',
  'donchian_channels': 'Canali di Donchian',
  'envelope': 'Envelope',
  'alligator': 'Alligator',
  'fractals': 'Frattali',
  'gator': 'Gator',
  'awesome_oscillator': 'Oscillatore Awesome',
  'accelerator': 'Acceleratore',
  'market_facilitation': 'Facilitazione del mercato',
  'zigzag': 'ZigZag',
  'elliott_wave': 'Onda di Elliott',
  'gann': 'Gann',
  'andrews_pitchfork': 'Forchetta di Andrews',
  'trendline': 'Linea di tendenza',
  'channel': 'Canale',
  'rectangle': 'Rettangolo',
  'triangle': 'Triangolo',
  'wedge': 'Cuneo',
  'flag': 'Bandiera',
  'pennant': 'Pennant',
  'head_shoulders': 'Testa e spalle',
  'double_top': 'Doppio massimo',
  'double_bottom': 'Doppio minimo',
  'triple_top': 'Triplo massimo',
  'triple_bottom': 'Triplo minimo',
  'cup_handle': 'Tazza con manico',
  'rounding_bottom': 'Fondo arrotondato',
  'ascending_triangle': 'Triangolo ascendente',
  'descending_triangle': 'Triangolo discendente',
  'symmetrical_triangle': 'Triangolo simmetrico',
  'rising_wedge': 'Cuneo ascendente',
  'falling_wedge': 'Cuneo discendente',
  'bull_flag': 'Bandiera rialzista',
  'bear_flag': 'Bandiera ribassista',
  'bull_pennant': 'Pennant rialzista',
  'bear_pennant': 'Pennant ribassista',
  'gap': 'Gap',
  'island_reversal': 'Inversione ad isola',
  'candlestick': 'Candela',
  'doji': 'Doji',
  'hammer': 'Martello',
  'hanging_man': 'Impiccato',
  'shooting_star': 'Stella cadente',
  'inverted_hammer': 'Martello invertito',
  'engulfing': 'Engulfing',
  'harami': 'Harami',
  'piercing': 'Piercing',
  'dark_cloud': 'Nuvola scura',
  'morning_star': 'Stella del mattino',
  'evening_star': 'Stella della sera',
  'three_white_soldiers': 'Tre soldati bianchi',
  'three_black_crows': 'Tre corvi neri',
  'spinning_top': 'Trottola',
  'marubozu': 'Marubozu',
  'tweezer': 'Pinzette',
  'abandoned_baby': 'Bambino abbandonato',
  'three_inside': 'Tre interni',
  'three_outside': 'Tre esterni',
  'rising_three': 'Tre ascendenti',
  'falling_three': 'Tre discendenti',
  'upside_gap': 'Gap rialzista',
  'downside_gap': 'Gap ribassista',
  'kicking': 'Kicking',
  'ladder': 'Scala',
  'three_line_strike': 'Colpo a tre linee',
  'two_crows': 'Due corvi',
  'unique_three_river': 'Tre fiumi unici',
  'concealing_baby_swallow': 'Rondine bambino nascosta',
  'stick_sandwich': 'Sandwich di bastoncini',
  'matching_low': 'Minimo corrispondente',
  'homing_pigeon': 'Piccione viaggiatore',
  'ladder_bottom': 'Fondo scala',
  'belt_hold': 'Presa cintura',
  'upside_tasuki_gap': 'Gap Tasuki rialzista',
  'downside_tasuki_gap': 'Gap Tasuki ribassista',
  'side_by_side': 'Fianco a fianco',
  'separating_lines': 'Linee di separazione',
  'in_neck': 'Nel collo',
  'on_neck': 'Sul collo',
  'thrusting': 'Spinta',
  'mat_hold': 'Tenuta tappeto',
  'breakaway': 'Fuga',
  'three_stars_south': 'Tre stelle del sud',
  'deliberation': 'Deliberazione',
  'advance_block': 'Blocco avanzato',
  'stalled_pattern': 'Pattern bloccato',
  'doji_star': 'Stella Doji',
  'dragonfly_doji': 'Doji libellula',
  'gravestone_doji': 'Doji lapide',
  'long_legged_doji': 'Doji dalle gambe lunghe',
  'rickshaw_man': 'Uomo risciò',
  'high_wave': 'Onda alta',
  'counterattack': 'Contrattacco',
  'meeting_lines': 'Linee di incontro',
};