const Map<String, String> es = {
  'login': 'Iniciar sesión',
  'create_account': 'Crear cuenta',
  'already_have_account': '¿Ya tienes una cuenta? Iniciar sesión',
  'name': 'Nombre',
  'email': 'Correo electrónico',
  'password': 'Contraseña',
  'birth_date': 'Fecha de nacimiento (AAAA-MM-DD)',
  'phone': 'Número de teléfono',
  'enter_name': 'Por favor ingrese su nombre',
  'enter_email': 'Por favor ingrese su correo electrónico',
  'invalid_email': 'Dirección de correo electrónico inválida',
  'enter_password': 'Por favor ingrese su contraseña',
  'password_too_short': 'La contraseña debe tener al menos 6 caracteres',
  'enter_birth_date': 'Por favor ingrese su fecha de nacimiento',
  'invalid_date': 'Formato de fecha inválido',
  'enter_phone': 'Por favor ingrese su número de teléfono',
  'age_restriction': 'Debes tener al menos 18 años',
  'auth_error': 'Error de autenticación',
  'account_created': 'Cuenta creada exitosamente',
  'chats': 'Chats',
  'hub': 'Hub',
  'converter': 'Convertidor',
  'news': 'Noticias',
  'profile': 'Perfil',
  'export_data': 'Exportar datos de usuario',
  'send_data': 'Enviar datos',
  'data_sent': 'Datos enviados exitosamente',
  'error_sending_data': 'Error al enviar datos',
  'type_message': 'Escribe tu mensaje...',
  'no_messages': 'Aún no hay mensajes.\n¡Sé el primero en enviar!',
  'error_loading_messages': 'Error al cargar mensajes',
  'hello': 'Hola',
  'portfolio': 'Portafolio',
  'quick_actions': 'Acciones rápidas',
  'send': 'Enviar',
  'receive': 'Recibir',
  'deposit': 'Depositar',
  'convert': 'Convertir',
  'watchlist': 'Lista de seguimiento',
  'no_watchlists': 'Aún no hay listas de seguimiento',
  'recent_alerts': 'Alertas recientes',
  'no_alerts': 'Aún no hay alertas',
  'activities': 'Actividades',
  'transactions': 'Transacciones',
  'orders': 'Órdenes',
  'alerts': 'Alertas',
  'reports': 'Informes',
  'no_transactions': 'Aún no hay transacciones',
  'no_orders': 'Aún no hay órdenes',
  'generate_report': 'Generar informe',
  'feed': 'Feed',
  'create_post': 'Crear publicación',
  'write_post': 'Escribe tu publicación...',
  'post': 'Publicar',
  'marketplace': 'Mercado',
  'bio': 'Biografía',
  'update_bio': 'Actualizar biografía',
  'statistics': 'Estadísticas',
  'points': 'Puntos',
  'followers': 'Seguidores',
  'settings': 'Configuración',
  'themes': 'Temas',
  'languages': 'Idiomas',
  'integrations': 'Integraciones',
  'security': 'Seguridad',
  'logout': 'Cerrar sesión',
  'charts': 'Gráficos',
  'screener': 'Filtrador',
  'calculators': 'Calculadoras',
  'journal': 'Diario',
  'strategies': 'Estrategias',
  'backtesting': 'Backtesting',
  'paper_trading': 'Trading en papel',
  'reminders': 'Recordatorios',
  'researcher': 'Investigador',
  'dictionary': 'Diccionario',
  'heatmaps': 'Mapas de calor',
  'correlation': 'Correlación',
  'football': 'Fútbol',
  'entertainment': 'Entretenimiento',
  'learning': 'Aprendizaje',
  'webinars': 'Webinars',
  'add_indicator': 'Agregar indicador',
  'filters': 'Filtros',
  'run_screener': 'Ejecutar filtrador',
  'results': 'Resultados',
  'position': 'Posición',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Puntos pivote',
  'risk_percentage': 'Porcentaje de riesgo',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calcular',
  'new_entry': 'Nueva entrada',
  'add_entry': 'Agregar entrada',
  'select_strategy': 'Seleccionar estrategia',
  'asset': 'Activo',
  'start_date': 'Fecha de inicio',
  'end_date': 'Fecha de fin',
  'run_backtest': 'Ejecutar backtest',
  'backtest_results': 'Resultados del backtest',
  'balance': 'Balance',
  'positions': 'Posiciones',
  'place_order': 'Colocar orden',
  'buy': 'Comprar',
  'sell': 'Vender',
  'quantity': 'Cantidad',
  'price': 'Precio',
  'title': 'Título',
  'date': 'Fecha',
  'add_reminder': 'Agregar recordatorio',
  'search_query': 'Consulta de búsqueda',
  'search': 'Buscar',
  'search_term': 'Término de búsqueda',
  'amount': 'Monto',
  'result': 'Resultado',
  'select_assets': 'Seleccionar activos',
  'calculate_correlation': 'Calcular correlación',
  'trading_simulator': 'Simulador de trading',
  'score': 'Puntuación',
  'start_game': 'Iniciar juego',
  'quiz': 'Cuestionario',
  'quiz_complete': 'Cuestionario completado',
  'movies': 'Películas',
  'menu': 'Menú',
  'error_loading': 'Error al cargar datos',
  'close': 'Cerrar',
};