const Map<String, String> ru = {
  'login': 'Войти',
  'create_account': 'Создать аккаунт',
  'already_have_account': 'Уже есть аккаунт? Войти',
  'name': 'Имя',
  'email': 'Электронная почта',
  'password': 'Пароль',
  'birth_date': 'Дата рождения (ГГГГ-ММ-ДД)',
  'phone': 'Номер телефона',
  'enter_name': 'Введите ваше имя',
  'enter_email': 'Введите ваш email',
  'invalid_email': 'Неверный адрес электронной почты',
  'enter_password': 'Введите ваш пароль',
  'password_too_short': 'Пароль должен содержать минимум 6 символов',
  'enter_birth_date': 'Введите дату рождения',
  'invalid_date': 'Неверный формат даты',
  'enter_phone': 'Введите номер телефона',
  'age_restriction': 'Вам должно быть не менее 18 лет',
  'auth_error': 'Ошибка аутентификации',
  'account_created': 'Аккаунт успешно создан',
  'chats': 'Чаты',
  'hub': 'Центр',
  'converter': 'Конвертер',
  'news': 'Новости',
  'profile': 'Профиль',
  'export_data': 'Экспорт данных пользователя',
  'send_data': 'Отправить данные',
  'data_sent': 'Данные успешно отправлены',
  'error_sending_data': 'Ошибка отправки данных',
  'type_message': 'Напишите сообщение...',
  'no_messages': 'Пока нет сообщений.\nБудьте первым!',
  'error_loading_messages': 'Ошибка загрузки сообщений',
  'hello': 'Привет',
  'portfolio': 'Портфель',
  'quick_actions': 'Быстрые действия',
  'send': 'Отправить',
  'receive': 'Получить',
  'deposit': 'Депозит',
  'convert': 'Конвертировать',
  'watchlist': 'Список наблюдения',
  'no_watchlists': 'Пока нет списков наблюдения',
  'recent_alerts': 'Недавние уведомления',
  'no_alerts': 'Пока нет уведомлений',
  'activities': 'Активность',
  'transactions': 'Транзакции',
  'orders': 'Ордера',
  'alerts': 'Уведомления',
  'reports': 'Отчёты',
  'no_transactions': 'Пока нет транзакций',
  'no_orders': 'Пока нет ордеров',
  'generate_report': 'Создать отчёт',
  'feed': 'Лента',
  'create_post': 'Создать публикацию',
  'write_post': 'Напишите публикацию...',
  'post': 'Опубликовать',
  'marketplace': 'Маркетплейс',
  'bio': 'Биография',
  'update_bio': 'Обновить биографию',
  'statistics': 'Статистика',
  'points': 'Очки',
  'followers': 'Подписчики',
  'settings': 'Настройки',
  'themes': 'Темы',
  'languages': 'Языки',
  'integrations': 'Интеграции',
  'security': 'Безопасность',
  'logout': 'Выйти',
  'charts': 'Графики',
  'screener': 'Скринер',
  'calculators': 'Калькуляторы',
  'journal': 'Журнал',
  'strategies': 'Стратегии',
  'backtesting': 'Бэктестинг',
  'paper_trading': 'Бумажная торговля',
  'reminders': 'Напоминания',
  'researcher': 'Исследователь',
  'dictionary': 'Словарь',
  'heatmaps': 'Тепловые карты',
  'correlation': 'Корреляция',
  'football': 'Футбол',
  'entertainment': 'Развлечения',
  'learning': 'Обучение',
  'webinars': 'Вебинары',
  'add_indicator': 'Добавить индикатор',
  'filters': 'Фильтры',
  'run_screener': 'Запустить скринер',
  'results': 'Результаты',
  'position': 'Позиция',
  'fibonacci': 'Фибоначчи',
  'pivot_points': 'Пивот-уровни',
  'risk_percentage': 'Процент риска',
  'stop_loss': 'Стоп-лосс',
  'calculate': 'Рассчитать',
  'new_entry': 'Новая запись',
  'add_entry': 'Добавить запись',
  'select_strategy': 'Выбрать стратегию',
  'asset': 'Актив',
  'start_date': 'Дата начала',
  'end_date': 'Дата окончания',
  'run_backtest': 'Запустить бэктест',
  'backtest_results': 'Результаты бэктеста',
  'balance': 'Баланс',
  'positions': 'Позиции',
  'place_order': 'Разместить ордер',
  'buy': 'Купить',
  'sell': 'Продать',
  'quantity': 'Количество',
  'price': 'Цена',
  'title': 'Заголовок',
  'date': 'Дата',
  'add_reminder': 'Добавить напоминание',
  'search_query': 'Поисковый запрос',
  'search': 'Поиск',
  'search_term': 'Поисковый термин',
  'amount': 'Сумма',
  'result': 'Результат',
  'select_assets': 'Выбрать активы',
  'calculate_correlation': 'Рассчитать корреляцию',
  'trading_simulator': 'Торговый симулятор',
  'score': 'Счёт',
  'start_game': 'Начать игру',
  'quiz': 'Викторина',
  'quiz_complete': 'Викторина завершена',
  'movies': 'Фильмы',
  'menu': 'Меню',
  'error_loading': 'Ошибка загрузки данных',
  'close': 'Закрыть',
  'send_receive': 'Отправить/Получить',
  'notifications': 'Уведомления',
  'performance_chart': 'График производительности',
  'order_book': 'Книга ордеров',
  'condition': 'Условие',
  'status': 'Статус',
  'description': 'Описание',
  'timestamp': 'Временная метка',
  'type': 'Тип',
  'active': 'Активный',
  'triggered': 'Сработал',
  'cancel': 'Отменить',
  'save': 'Сохранить',
  'edit': 'Редактировать',
  'delete': 'Удалить',
  'confirm': 'Подтвердить',
  'success': 'Успех',
  'error': 'Ошибка',
  'warning': 'Предупреждение',
  'info': 'Информация',
  'loading': 'Загрузка...',
  'no_data': 'Нет данных',
  'refresh': 'Обновить',
  'filter': 'Фильтр',
  'sort': 'Сортировать',
  'ascending': 'По возрастанию',
  'descending': 'По убыванию',
  'all': 'Все',
  'none': 'Нет',
  'select': 'Выбрать',
  'selected': 'Выбрано',
  'deselect': 'Снять выбор',
  'apply': 'Применить',
  'reset': 'Сбросить',
  'clear': 'Очистить',
  'done': 'Готово',
  'next': 'Далее',
  'previous': 'Назад',
  'skip': 'Пропустить',
  'finish': 'Завершить',
  'yes': 'Да',
  'no': 'Нет',
  'ok': 'ОК',
  'got_it': 'Понятно',
  'learn_more': 'Узнать больше',
  'see_all': 'Посмотреть всё',
  'show_more': 'Показать больше',
  'show_less': 'Показать меньше',
  'expand': 'Развернуть',
  'collapse': 'Свернуть',
  'open': 'Открыть',
  'share': 'Поделиться',
  'copy': 'Копировать',
  'paste': 'Вставить',
  'cut': 'Вырезать',
  'undo': 'Отменить',
  'redo': 'Повторить',
  'upload': 'Загрузить',
  'download': 'Скачать',
  'print': 'Печать',
  'preview': 'Предпросмотр',
  'view': 'Просмотр',
  'details': 'Детали',
  'more': 'Больше',
  'less': 'Меньше',
  'help': 'Помощь',
  'about': 'О программе',
  'version': 'Версия',
  'terms': 'Условия',
  'privacy': 'Конфиденциальность',
  'contact': 'Контакты',
  'support': 'Поддержка',
  'feedback': 'Обратная связь',
  'rate_app': 'Оценить приложение',
  'update': 'Обновить',
  'new_version': 'Новая версия',
  'required': 'Обязательно',
  'optional': 'Необязательно',
  'recommended': 'Рекомендуется',
  'popular': 'Популярное',
  'trending': 'В тренде',
  'new': 'Новое',
  'featured': 'Избранное',
  'top': 'Топ',
  'best': 'Лучшее',
  'latest': 'Последнее',
  'recent': 'Недавнее',
  'today': 'Сегодня',
  'yesterday': 'Вчера',
  'this_week': 'На этой неделе',
  'this_month': 'В этом месяце',
  'this_year': 'В этом году',
  'last_week': 'На прошлой неделе',
  'last_month': 'В прошлом месяце',
  'last_year': 'В прошлом году',
  'custom': 'Пользовательский',
  'default': 'По умолчанию',
  'enabled': 'Включено',
  'disabled': 'Отключено',
  'on': 'Вкл',
  'off': 'Выкл',
  'automatic': 'Автоматически',
  'manual': 'Вручную',
  'always': 'Всегда',
  'never': 'Никогда',
  'ask': 'Спросить',
  'light': 'Светлая',
  'dark': 'Тёмная',
  'system': 'Системная',
  'high': 'Высокий',
  'medium': 'Средний',
  'low': 'Низкий',
  'very_high': 'Очень высокий',
  'very_low': 'Очень низкий',
  'maximum': 'Максимум',
  'minimum': 'Минимум',
  'unlimited': 'Неограниченно',
  'limited': 'Ограничено',
  'free': 'Бесплатно',
  'premium': 'Премиум',
  'pro': 'Про',
  'basic': 'Базовый',
  'standard': 'Стандарт',
  'advanced': 'Продвинутый',
  'beginner': 'Начинающий',
  'intermediate': 'Средний',
  'expert': 'Эксперт',
  'easy': 'Легко',
  'normal': 'Нормально',
  'hard': 'Сложно',
  'complete': 'Завершено',
  'incomplete': 'Не завершено',
  'pending': 'В ожидании',
  'approved': 'Одобрено',
  'rejected': 'Отклонено',
  'cancelled': 'Отменено',
  'failed': 'Не удалось',
  'processing': 'Обработка',
  'completed': 'Выполнено',
  'verified': 'Подтверждено',
  'unverified': 'Не подтверждено',
  'connected': 'Подключено',
  'disconnected': 'Отключено',
  'online': 'Онлайн',
  'offline': 'Офлайн',
  'available': 'Доступно',
  'unavailable': 'Недоступно',
  'in_stock': 'В наличии',
  'out_of_stock': 'Нет в наличии',
  'coming_soon': 'Скоро',
  'maintenance': 'Обслуживание',
  'emergency': 'Срочно',
  'scheduled': 'Запланировано',
  'unscheduled': 'Не запланировано',
  'public': 'Публичный',
  'private': 'Приватный',
  'draft': 'Черновик',
  'published': 'Опубликовано',
  'archived': 'Архивировано',
  'deleted': 'Удалено',
  'restored': 'Восстановлено',
  'backup': 'Резервная копия',
  'import': 'Импорт',
  'export': 'Экспорт',
  'sync': 'Синхронизация',
  'syncing': 'Синхронизируется',
  'synced': 'Синхронизировано',
  'not_synced': 'Не синхронизировано',
  'sync_failed': 'Синхронизация не удалась',
  'retry': 'Повторить',
  'try_again': 'Попробовать снова',
  'continue': 'Продолжить',
  'back': 'Назад',
  'home': 'Главная',
  'dashboard': 'Панель',
  'overview': 'Обзор',
  'summary': 'Сводка',
  'list': 'Список',
  'grid': 'Сетка',
  'table': 'Таблица',
  'calendar': 'Календарь',
  'map': 'Карта',
  'graph': 'График',
  'chart': 'График',
  'report': 'Отчёт',
  'analytics': 'Аналитика',
  'insights': 'Инсайты',
  'trends': 'Тренды',
  'comparison': 'Сравнение',
  'performance': 'Производительность',
  'growth': 'Рост',
  'decline': 'Падение',
  'change': 'Изменение',
  'increase': 'Увеличение',
  'decrease': 'Уменьшение',
  'percentage': 'Процент',
  'value': 'Значение',
  'total': 'Итого',
  'subtotal': 'Промежуточный итог',
  'average': 'Среднее',
  'median': 'Медиана',
  'mode': 'Мода',
  'range': 'Диапазон',
  'sum': 'Сумма',
  'count': 'Количество',
  'frequency': 'Частота',
  'rate': 'Ставка',
  'ratio': 'Соотношение',
  'profit': 'Прибыль',
  'loss': 'Убыток',
  'revenue': 'Доход',
  'expense': 'Расход',
  'income': 'Доход',
  'cost': 'Стоимость',
  'fee': 'Комиссия',
  'tax': 'Налог',
  'discount': 'Скидка',
  'commission': 'Комиссия',
  'interest': 'Процент',
  'dividend': 'Дивиденд',
  'bonus': 'Бонус',
  'reward': 'Награда',
  'penalty': 'Штраф',
  'credit': 'Кредит',
  'debit': 'Дебет',
  'payment': 'Платёж',
  'refund': 'Возврат',
  'withdrawal': 'Вывод',
  'transfer': 'Перевод',
  'exchange': 'Обмен',
  'trade': 'Сделка',
  'investment': 'Инвестиция',
  'savings': 'Сбережения',
  'account': 'Счёт',
  'wallet': 'Кошелёк',
  'card': 'Карта',
  'bank': 'Банк',
  'currency': 'Валюта',
  'crypto': 'Крипто',
  'stock': 'Акция',
  'bond': 'Облигация',
  'commodity': 'Сырьё',
  'forex': 'Форекс',
  'index': 'Индекс',
  'etf': 'ETF',
  'mutual_fund': 'Взаимный фонд',
  'real_estate': 'Недвижимость',
  'option': 'Опцион',
  'future': 'Фьючерс',
  'derivative': 'Дериватив',
  'security': 'Ценная бумага',
  'instrument': 'Инструмент',
  'market': 'Рынок',
  'exchange_market': 'Биржа',
  'broker': 'Брокер',
  'dealer': 'Дилер',
  'trader': 'Трейдер',
  'investor': 'Инвестор',
  'buyer': 'Покупатель',
  'seller': 'Продавец',
  'bid': 'Покупка',
  'ask': 'Продажа',
  'spread': 'Спред',
  'volume': 'Объём',
  'liquidity': 'Ликвидность',
  'volatility': 'Волатильность',
  'trend': 'Тренд',
  'bullish': 'Бычий',
  'bearish': 'Медвежий',
  'neutral': 'Нейтральный',
  'support': 'Поддержка',
  'resistance': 'Сопротивление',
  'breakout': 'Пробой',
  'breakdown': 'Пробой вниз',
  'reversal': 'Разворот',
  'continuation': 'Продолжение',
  'pattern': 'Паттерн',
  'signal': 'Сигнал',
  'indicator': 'Индикатор',
  'oscillator': 'Осциллятор',
  'moving_average': 'Скользящая средняя',
  'rsi': 'RSI',
  'macd': 'MACD',
  'bollinger_bands': 'Полосы Боллинджера',
  'stochastic': 'Стохастик',
  'adx': 'ADX',
  'atr': 'ATR',
  'cci': 'CCI',
  'williams_r': 'Williams %R',
  'momentum': 'Импульс',
  'roc': 'ROC',
  'obv': 'OBV',
  'vwap': 'VWAP',
  'ema': 'EMA',
  'sma': 'SMA',
  'wma': 'WMA',
  'hma': 'HMA',
  'ichimoku': 'Ишимоку',
  'parabolic_sar': 'Параболик SAR',
  'keltner_channels': 'Каналы Кельтнера',
  'donchian_channels': 'Каналы Дончиана',
  'envelope': 'Конверт',
  'alligator': 'Аллигатор',
  'fractals': 'Фракталы',
  'gator': 'Гатор',
  'awesome_oscillator': 'Awesome Oscillator',
  'accelerator': 'Ускоритель',
  'market_facilitation': 'Облегчение рынка',
  'zigzag': 'Зигзаг',
  'elliott_wave': 'Волны Эллиотта',
  'gann': 'Ганн',
  'andrews_pitchfork': 'Вилы Эндрюса',
  'trendline': 'Линия тренда',
  'channel': 'Канал',
  'rectangle': 'Прямоугольник',
  'triangle': 'Треугольник',
  'wedge': 'Клин',
  'flag': 'Флаг',
  'pennant': 'Вымпел',
  'head_shoulders': 'Голова и плечи',
  'double_top': 'Двойная вершина',
  'double_bottom': 'Двойное дно',
  'triple_top': 'Тройная вершина',
  'triple_bottom': 'Тройное дно',
  'cup_handle': 'Чашка с ручкой',
  'rounding_bottom': 'Закруглённое дно',
  'ascending_triangle': 'Восходящий треугольник',
  'descending_triangle': 'Нисходящий треугольник',
  'symmetrical_triangle': 'Симметричный треугольник',
  'rising_wedge': 'Восходящий клин',
  'falling_wedge': 'Нисходящий клин',
  'bull_flag': 'Бычий флаг',
  'bear_flag': 'Медвежий флаг',
  'bull_pennant': 'Бычий вымпел',
  'bear_pennant': 'Медвежий вымпел',
  'gap': 'Гэп',
  'island_reversal': 'Островной разворот',
  'candlestick': 'Свеча',
  'doji': 'Доджи',
  'hammer': 'Молот',
  'hanging_man': 'Висельник',
  'shooting_star': 'Падающая звезда',
  'inverted_hammer': 'Перевёрнутый молот',
  'engulfing': 'Поглощение',
  'harami': 'Харами',
  'piercing': 'Просвет в облаках',
  'dark_cloud': 'Завеса из тёмных облаков',
  'morning_star': 'Утренняя звезда',
  'evening_star': 'Вечерняя звезда',
  'three_white_soldiers': 'Три белых солдата',
  'three_black_crows': 'Три чёрные вороны',
  'spinning_top': 'Волчок',
  'marubozu': 'Марубозу',
  'tweezer': 'Пинцет',
  'abandoned_baby': 'Брошенный младенец',
  'three_inside': 'Три внутри',
  'three_outside': 'Три снаружи',
  'rising_three': 'Три наступающих',
  'falling_three': 'Три отступающих',
  'upside_gap': 'Гэп вверх',
  'downside_gap': 'Гэп вниз',
  'kicking': 'Пинок',
  'ladder': 'Лестница',
  'three_line_strike': 'Удар трёх линий',
  'two_crows': 'Две вороны',
  'unique_three_river': 'Уникальные три реки',
  'concealing_baby_swallow': 'Скрывающая ласточка',
  'stick_sandwich': 'Сэндвич',
  'matching_low': 'Совпадающий минимум',
  'homing_pigeon': 'Почтовый голубь',
  'ladder_bottom': 'Лестница внизу',
  'belt_hold': 'Захват за пояс',
  'upside_tasuki_gap': 'Гэп Тасуки вверх',
  'downside_tasuki_gap': 'Гэп Тасуки вниз',
  'side_by_side': 'Бок о бок',
  'separating_lines': 'Разделяющие линии',
  'in_neck': 'В шее',
  'on_neck': 'На шее',
  'thrusting': 'Толчок',
  'mat_hold': 'Удержание мата',
  'breakaway': 'Отрыв',
  'three_stars_south': 'Три звезды на юге',
  'deliberation': 'Обсуждение',
  'advance_block': 'Блок продвижения',
  'stalled_pattern': 'Застопорившийся паттерн',
  'doji_star': 'Звезда доджи',
  'dragonfly_doji': 'Доджи-стрекоза',
  'gravestone_doji': 'Доджи-надгробие',
  'long_legged_doji': 'Длинноногий доджи',
  'rickshaw_man': 'Рикша',
  'high_wave': 'Высокая волна',
  'counterattack': 'Контратака',
  'meeting_lines': 'Встречные линии',
};