const Map<String, String> pt = {
  'login': 'Entrar',
  'create_account': 'Criar conta',
  'already_have_account': 'Já tem uma conta? Entrar',
  'name': 'Nome',
  'email': 'Email',
  'password': 'Senha',
  'birth_date': 'Data de nascimento (AAAA-MM-DD)',
  'phone': 'Número de telefone',
  'enter_name': 'Por favor, insira seu nome',
  'enter_email': 'Por favor, insira seu email',
  'invalid_email': 'Endereço de email inválido',
  'enter_password': 'Por favor, insira sua senha',
  'password_too_short': 'A senha deve ter pelo menos 6 caracteres',
  'enter_birth_date': 'Por favor, insira sua data de nascimento',
  'invalid_date': 'Formato de data inválido',
  'enter_phone': 'Por favor, insira seu número de telefone',
  'age_restriction': 'Você deve ter pelo menos 18 anos',
  'auth_error': 'Erro de autenticação',
  'account_created': 'Conta criada com sucesso',
  'chats': 'Conversas',
  'hub': 'Hub',
  'converter': 'Conversor',
  'news': 'Notícias',
  'profile': 'Perfil',
  'export_data': 'Exportar dados do usuário',
  'send_data': 'Enviar dados',
  'data_sent': 'Dados enviados com sucesso',
  'error_sending_data': 'Erro ao enviar dados',
  'type_message': 'Digite sua mensagem...',
  'no_messages': 'Ainda não há mensagens.\nSeja o primeiro a enviar!',
  'error_loading_messages': 'Erro ao carregar mensagens',
  'hello': 'Olá',
  'portfolio': 'Portfólio',
  'quick_actions': 'Ações rápidas',
  'send': 'Enviar',
  'receive': 'Receber',
  'deposit': 'Depositar',
  'convert': 'Converter',
  'watchlist': 'Lista de observação',
  'no_watchlists': 'Ainda não há listas de observação',
  'recent_alerts': 'Alertas recentes',
  'no_alerts': 'Ainda não há alertas',
  'activities': 'Atividades',
  'transactions': 'Transações',
  'orders': 'Ordens',
  'alerts': 'Alertas',
  'reports': 'Relatórios',
  'no_transactions': 'Ainda não há transações',
  'no_orders': 'Ainda não há ordens',
  'generate_report': 'Gerar relatório',
  'feed': 'Feed',
  'create_post': 'Criar publicação',
  'write_post': 'Escreva sua publicação...',
  'post': 'Publicar',
  'marketplace': 'Mercado',
  'bio': 'Biografia',
  'update_bio': 'Atualizar biografia',
  'statistics': 'Estatísticas',
  'points': 'Pontos',
  'followers': 'Seguidores',
  'settings': 'Configurações',
  'themes': 'Temas',
  'languages': 'Idiomas',
  'integrations': 'Integrações',
  'security': 'Segurança',
  'logout': 'Sair',
  'charts': 'Gráficos',
  'screener': 'Filtrador',
  'calculators': 'Calculadoras',
  'journal': 'Diário',
  'strategies': 'Estratégias',
  'backtesting': 'Backtesting',
  'paper_trading': 'Trading simulado',
  'reminders': 'Lembretes',
  'researcher': 'Pesquisador',
  'dictionary': 'Dicionário',
  'heatmaps': 'Mapas de calor',
  'correlation': 'Correlação',
  'football': 'Futebol',
  'entertainment': 'Entretenimento',
  'learning': 'Aprendizado',
  'webinars': 'Webinars',
  'add_indicator': 'Adicionar indicador',
  'filters': 'Filtros',
  'run_screener': 'Executar filtrador',
  'results': 'Resultados',
  'position': 'Posição',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Pontos pivô',
  'risk_percentage': 'Percentual de risco',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calcular',
  'new_entry': 'Nova entrada',
  'add_entry': 'Adicionar entrada',
  'select_strategy': 'Selecionar estratégia',
  'asset': 'Ativo',
  'start_date': 'Data de início',
  'end_date': 'Data de término',
  'run_backtest': 'Executar backtest',
  'backtest_results': 'Resultados do backtest',
  'balance': 'Saldo',
  'positions': 'Posições',
  'place_order': 'Fazer pedido',
  'buy': 'Comprar',
  'sell': 'Vender',
  'quantity': 'Quantidade',
  'price': 'Preço',
  'title': 'Título',
  'date': 'Data',
  'add_reminder': 'Adicionar lembrete',
  'search_query': 'Consulta de pesquisa',
  'search': 'Pesquisar',
  'search_term': 'Termo de pesquisa',
  'amount': 'Valor',
  'result': 'Resultado',
  'select_assets': 'Selecionar ativos',
  'calculate_correlation': 'Calcular correlação',
  'trading_simulator': 'Simulador de trading',
  'score': 'Pontuação',
  'start_game': 'Iniciar jogo',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz completo',
  'movies': 'Filmes',
  'menu': 'Menu',
  'error_loading': 'Erro ao carregar dados',
  'close': 'Fechar',
};