const Map<String, String> fr = {
  'login': 'Connexion',
  'create_account': 'Créer un compte',
  'already_have_account': 'Vous avez déjà un compte? Connectez-vous',
  'name': 'Nom',
  'email': 'Email',
  'password': 'Mot de passe',
  'birth_date': 'Date de naissance (AAAA-MM-JJ)',
  'phone': 'Numéro de téléphone',
  'enter_name': 'Veuillez entrer votre nom',
  'enter_email': 'Veuillez entrer votre email',
  'invalid_email': 'Adresse email invalide',
  'enter_password': 'Veuillez entrer votre mot de passe',
  'password_too_short': 'Le mot de passe doit contenir au moins 6 caractères',
  'enter_birth_date': 'Veuillez entrer votre date de naissance',
  'invalid_date': 'Format de date invalide',
  'enter_phone': 'Veuillez entrer votre numéro de téléphone',
  'age_restriction': 'Vous devez avoir au moins 18 ans',
  'auth_error': 'Erreur d\'authentification',
  'account_created': 'Compte créé avec succès',
  'chats': 'Discussions',
  'hub': 'Hub',
  'converter': 'Convertisseur',
  'news': 'Actualités',
  'profile': 'Profil',
  'export_data': 'Exporter les données utilisateur',
  'send_data': 'Envoyer les données',
  'data_sent': 'Données envoyées avec succès',
  'error_sending_data': 'Erreur lors de l\'envoi des données',
  'type_message': 'Tapez votre message...',
  'no_messages': 'Pas encore de messages.\nSoyez le premier à envoyer!',
  'error_loading_messages': 'Erreur lors du chargement des messages',
  'hello': 'Bonjour',
  'portfolio': 'Portefeuille',
  'quick_actions': 'Actions rapides',
  'send': 'Envoyer',
  'receive': 'Recevoir',
  'deposit': 'Dépôt',
  'convert': 'Convertir',
  'watchlist': 'Liste de surveillance',
  'no_watchlists': 'Pas encore de listes de surveillance',
  'recent_alerts': 'Alertes récentes',
  'no_alerts': 'Pas encore d\'alertes',
  'activities': 'Activités',
  'transactions': 'Transactions',
  'orders': 'Ordres',
  'alerts': 'Alertes',
  'reports': 'Rapports',
  'no_transactions': 'Pas encore de transactions',
  'no_orders': 'Pas encore d\'ordres',
  'generate_report': 'Générer un rapport',
  'feed': 'Fil d\'actualité',
  'create_post': 'Créer une publication',
  'write_post': 'Écrivez votre publication...',
  'post': 'Publication',
  'marketplace': 'Marché',
  'bio': 'Biographie',
  'update_bio': 'Mettre à jour la biographie',
  'statistics': 'Statistiques',
  'points': 'Points',
  'followers': 'Abonnés',
  'settings': 'Paramètres',
  'themes': 'Thèmes',
  'languages': 'Langues',
  'integrations': 'Intégrations',
  'security': 'Sécurité',
  'logout': 'Déconnexion',
  'charts': 'Graphiques',
  'screener': 'Screener',
  'calculators': 'Calculatrices',
  'journal': 'Journal',
  'strategies': 'Stratégies',
  'backtesting': 'Backtesting',
  'paper_trading': 'Trading papier',
  'reminders': 'Rappels',
  'researcher': 'Chercheur',
  'dictionary': 'Dictionnaire',
  'heatmaps': 'Cartes thermiques',
  'correlation': 'Corrélation',
  'football': 'Football',
  'entertainment': 'Divertissement',
  'learning': 'Apprentissage',
  'webinars': 'Webinaires',
  'add_indicator': 'Ajouter un indicateur',
  'filters': 'Filtres',
  'run_screener': 'Exécuter le screener',
  'results': 'Résultats',
  'position': 'Position',
  'fibonacci': 'Fibonacci',
  'pivot_points': 'Points pivots',
  'risk_percentage': 'Pourcentage de risque',
  'stop_loss': 'Stop Loss',
  'calculate': 'Calculer',
  'new_entry': 'Nouvelle entrée',
  'add_entry': 'Ajouter une entrée',
  'select_strategy': 'Sélectionner une stratégie',
  'asset': 'Actif',
  'start_date': 'Date de début',
  'end_date': 'Date de fin',
  'run_backtest': 'Exécuter le backtest',
  'backtest_results': 'Résultats du backtest',
  'balance': 'Solde',
  'positions': 'Positions',
  'place_order': 'Placer un ordre',
  'buy': 'Acheter',
  'sell': 'Vendre',
  'quantity': 'Quantité',
  'price': 'Prix',
  'title': 'Titre',
  'date': 'Date',
  'add_reminder': 'Ajouter un rappel',
  'search_query': 'Requête de recherche',
  'search': 'Rechercher',
  'search_term': 'Terme de recherche',
  'amount': 'Montant',
  'result': 'Résultat',
  'select_assets': 'Sélectionner des actifs',
  'calculate_correlation': 'Calculer la corrélation',
  'trading_simulator': 'Simulateur de trading',
  'score': 'Score',
  'start_game': 'Démarrer le jeu',
  'quiz': 'Quiz',
  'quiz_complete': 'Quiz terminé',
  'movies': 'Films',
  'menu': 'Menu',
  'error_loading': 'Erreur lors du chargement des données',
  'close': 'Fermer',
  'send_receive': 'Envoyer/Recevoir',
  'notifications': 'Notifications',
  'performance_chart': 'Graphique de performance',
  'order_book': 'Carnet d\'ordres',
  'condition': 'Condition',
  'status': 'Statut',
  'description': 'Description',
  'timestamp': 'Horodatage',
  'type': 'Type',
  'active': 'Actif',
  'triggered': 'Déclenché',
  'cancel': 'Annuler',
  'save': 'Enregistrer',
  'edit': 'Modifier',
  'delete': 'Supprimer',
  'confirm': 'Confirmer',
  'success': 'Succès',
  'error': 'Erreur',
  'warning': 'Avertissement',
  'info': 'Information',
  'loading': 'Chargement...',
  'no_data': 'Aucune donnée disponible',
  'refresh': 'Actualiser',
  'filter': 'Filtrer',
  'sort': 'Trier',
  'ascending': 'Croissant',
  'descending': 'Décroissant',
  'all': 'Tout',
  'none': 'Aucun',
  'select': 'Sélectionner',
  'selected': 'Sélectionné',
  'deselect': 'Désélectionner',
  'apply': 'Appliquer',
  'reset': 'Réinitialiser',
  'clear': 'Effacer',
  'done': 'Terminé',
  'next': 'Suivant',
  'previous': 'Précédent',
  'skip': 'Passer',
  'finish': 'Terminer',
  'yes': 'Oui',
  'no': 'Non',
  'ok': 'OK',
  'got_it': 'Compris',
  'learn_more': 'En savoir plus',
  'see_all': 'Voir tout',
  'show_more': 'Afficher plus',
  'show_less': 'Afficher moins',
  'expand': 'Développer',
  'collapse': 'Réduire',
  'open': 'Ouvrir',
  'share': 'Partager',
  'copy': 'Copier',
  'paste': 'Coller',
  'cut': 'Couper',
  'undo': 'Annuler',
  'redo': 'Refaire',
  'upload': 'Télécharger',
  'download': 'Télécharger',
  'print': 'Imprimer',
  'preview': 'Aperçu',
  'view': 'Voir',
  'details': 'Détails',
  'more': 'Plus',
  'less': 'Moins',
  'help': 'Aide',
  'about': 'À propos',
  'version': 'Version',
  'terms': 'Conditions',
  'privacy': 'Confidentialité',
  'contact': 'Contact',
  'feedback': 'Commentaires',
  'rate_app': 'Évaluer l\'application',
  'update': 'Mettre à jour',
  'new_version': 'Nouvelle version',
  'required': 'Requis',
  'optional': 'Optionnel',
  'recommended': 'Recommandé',
  'popular': 'Populaire',
  'trending': 'Tendance',
  'new': 'Nouveau',
  'featured': 'En vedette',
  'top': 'Top',
  'best': 'Meilleur',
  'latest': 'Dernier',
  'recent': 'Récent',
  'today': 'Aujourd\'hui',
  'yesterday': 'Hier',
  'this_week': 'Cette semaine',
  'this_month': 'Ce mois-ci',
  'this_year': 'Cette année',
  'last_week': 'Semaine dernière',
  'last_month': 'Mois dernier',
  'last_year': 'Année dernière',
  'custom': 'Personnalisé',
  'default': 'Par défaut',
  'enabled': 'Activé',
  'disabled': 'Désactivé',
  'on': 'Activé',
  'off': 'Désactivé',
  'automatic': 'Automatique',
  'manual': 'Manuel',
  'always': 'Toujours',
  'never': 'Jamais',
  'ask': 'Demander',
  'light': 'Clair',
  'dark': 'Sombre',
  'system': 'Système',
  'high': 'Élevé',
  'medium': 'Moyen',
  'low': 'Faible',
  'very_high': 'Très élevé',
  'very_low': 'Très faible',
  'maximum': 'Maximum',
  'minimum': 'Minimum',
  'unlimited': 'Illimité',
  'limited': 'Limité',
  'free': 'Gratuit',
  'premium': 'Premium',
  'pro': 'Pro',
  'basic': 'Basique',
  'standard': 'Standard',
  'advanced': 'Avancé',
  'beginner': 'Débutant',
  'intermediate': 'Intermédiaire',
  'expert': 'Expert',
  'easy': 'Facile',
  'normal': 'Normal',
  'hard': 'Difficile',
  'complete': 'Complet',
  'incomplete': 'Incomplet',
  'pending': 'En attente',
  'approved': 'Approuvé',
  'rejected': 'Rejeté',
  'cancelled': 'Annulé',
  'failed': 'Échoué',
  'processing': 'Traitement',
  'completed': 'Terminé',
  'verified': 'Vérifié',
  'unverified': 'Non vérifié',
  'connected': 'Connecté',
  'disconnected': 'Déconnecté',
  'online': 'En ligne',
  'offline': 'Hors ligne',
  'available': 'Disponible',
  'unavailable': 'Indisponible',
  'in_stock': 'En stock',
  'out_of_stock': 'Rupture de stock',
  'coming_soon': 'Bientôt disponible',
  'maintenance': 'Maintenance',
  'emergency': 'Urgence',
  'scheduled': 'Programmé',
  'unscheduled': 'Non programmé',
  'public': 'Public',
  'private': 'Privé',
  'draft': 'Brouillon',
  'published': 'Publié',
  'archived': 'Archivé',
  'deleted': 'Supprimé',
  'restored': 'Restauré',
  'backup': 'Sauvegarde',
  'import': 'Importer',
  'export': 'Exporter',
  'sync': 'Synchroniser',
  'syncing': 'Synchronisation',
  'synced': 'Synchronisé',
  'not_synced': 'Non synchronisé',
  'sync_failed': 'Échec de la synchronisation',
  'retry': 'Réessayer',
  'try_again': 'Réessayer',
  'continue': 'Continuer',
  'back': 'Retour',
  'home': 'Accueil',
  'dashboard': 'Tableau de bord',
  'overview': 'Vue d\'ensemble',
  'summary': 'Résumé',
  'list': 'Liste',
  'grid': 'Grille',
  'table': 'Tableau',
  'calendar': 'Calendrier',
  'map': 'Carte',
  'graph': 'Graphique',
  'chart': 'Graphique',
  'report': 'Rapport',
  'analytics': 'Analytique',
  'insights': 'Informations',
  'trends': 'Tendances',
  'comparison': 'Comparaison',
  'performance': 'Performance',
  'growth': 'Croissance',
  'decline': 'Déclin',
  'change': 'Changement',
  'increase': 'Augmentation',
  'decrease': 'Diminution',
  'percentage': 'Pourcentage',
  'value': 'Valeur',
  'total': 'Total',
  'subtotal': 'Sous-total',
  'average': 'Moyenne',
  'median': 'Médiane',
  'mode': 'Mode',
  'range': 'Plage',
  'sum': 'Somme',
  'count': 'Compte',
  'frequency': 'Fréquence',
  'rate': 'Taux',
  'ratio': 'Ratio',
  'profit': 'Profit',
  'loss': 'Perte',
  'revenue': 'Revenu',
  'expense': 'Dépense',
  'income': 'Revenu',
  'cost': 'Coût',
  'fee': 'Frais',
  'tax': 'Taxe',
  'discount': 'Remise',
  'commission': 'Commission',
  'interest': 'Intérêt',
  'dividend': 'Dividende',
  'bonus': 'Bonus',
  'reward': 'Récompense',
  'penalty': 'Pénalité',
  'credit': 'Crédit',
  'debit': 'Débit',
  'payment': 'Paiement',
  'refund': 'Remboursement',
  'withdrawal': 'Retrait',
  'transfer': 'Transfert',
  'exchange': 'Échange',
  'trade': 'Commerce',
  'investment': 'Investissement',
  'savings': 'Épargne',
  'account': 'Compte',
  'wallet': 'Portefeuille',
  'card': 'Carte',
  'bank': 'Banque',
  'currency': 'Devise',
  'crypto': 'Crypto',
  'stock': 'Action',
  'bond': 'Obligation',
  'commodity': 'Matière première',
  'forex': 'Forex',
  'index': 'Indice',
  'etf': 'ETF',
  'mutual_fund': 'Fonds commun',
  'real_estate': 'Immobilier',
  'option': 'Option',
  'future': 'Future',
  'derivative': 'Dérivé',
  'security': 'Titre',
  'instrument': 'Instrument',
  'market': 'Marché',
  'exchange_market': 'Bourse',
  'broker': 'Courtier',
  'dealer': 'Négociant',
  'trader': 'Trader',
  'investor': 'Investisseur',
  'buyer': 'Acheteur',
  'seller': 'Vendeur',
  'bid': 'Offre',
  'ask': 'Demande',
  'spread': 'Écart',
  'volume': 'Volume',
  'liquidity': 'Liquidité',
  'volatility': 'Volatilité',
  'trend': 'Tendance',
  'bullish': 'Haussier',
  'bearish': 'Baissier',
  'neutral': 'Neutre',
  'support': 'Support',
  'resistance': 'Résistance',
  'breakout': 'Percée',
  'breakdown': 'Effondrement',
  'reversal': 'Retournement',
  'continuation': 'Continuation',
  'pattern': 'Motif',
  'signal': 'Signal',
  'indicator': 'Indicateur',
  'oscillator': 'Oscillateur',
  'moving_average': 'Moyenne mobile',
  'rsi': 'RSI',
  'macd': 'MACD',
  'bollinger_bands': 'Bandes de Bollinger',
  'stochastic': 'Stochastique',
  'adx': 'ADX',
  'atr': 'ATR',
  'cci': 'CCI',
  'williams_r': 'Williams %R',
  'momentum': 'Momentum',
  'roc': 'ROC',
  'obv': 'OBV',
  'vwap': 'VWAP',
  'ema': 'EMA',
  'sma': 'SMA',
  'wma': 'WMA',
  'hma': 'HMA',
  'ichimoku': 'Ichimoku',
  'parabolic_sar': 'SAR Parabolique',
  'keltner_channels': 'Canaux de Keltner',
  'donchian_channels': 'Canaux de Donchian',
  'envelope': 'Enveloppe',
  'alligator': 'Alligator',
  'fractals': 'Fractales',
  'gator': 'Gator',
  'awesome_oscillator': 'Oscillateur Awesome',
  'accelerator': 'Accélérateur',
  'market_facilitation': 'Facilitation du marché',
  'zigzag': 'ZigZag',
  'elliott_wave': 'Vague d\'Elliott',
  'gann': 'Gann',
  'andrews_pitchfork': 'Fourche d\'Andrews',
  'trendline': 'Ligne de tendance',
  'channel': 'Canal',
  'rectangle': 'Rectangle',
  'triangle': 'Triangle',
  'wedge': 'Biseau',
  'flag': 'Drapeau',
  'pennant': 'Fanion',
  'head_shoulders': 'Tête et épaules',
  'double_top': 'Double sommet',
  'double_bottom': 'Double creux',
  'triple_top': 'Triple sommet',
  'triple_bottom': 'Triple creux',
  'cup_handle': 'Tasse avec anse',
  'rounding_bottom': 'Creux arrondi',
  'ascending_triangle': 'Triangle ascendant',
  'descending_triangle': 'Triangle descendant',
  'symmetrical_triangle': 'Triangle symétrique',
  'rising_wedge': 'Biseau ascendant',
  'falling_wedge': 'Biseau descendant',
  'bull_flag': 'Drapeau haussier',
  'bear_flag': 'Drapeau baissier',
  'bull_pennant': 'Fanion haussier',
  'bear_pennant': 'Fanion baissier',
  'gap': 'Gap',
  'island_reversal': 'Retournement d\'île',
  'candlestick': 'Chandelier',
  'doji': 'Doji',
  'hammer': 'Marteau',
  'hanging_man': 'Pendu',
  'shooting_star': 'Étoile filante',
  'inverted_hammer': 'Marteau inversé',
  'engulfing': 'Engloutissant',
  'harami': 'Harami',
  'piercing': 'Perçant',
  'dark_cloud': 'Nuage noir',
  'morning_star': 'Étoile du matin',
  'evening_star': 'Étoile du soir',
  'three_white_soldiers': 'Trois soldats blancs',
  'three_black_crows': 'Trois corbeaux noirs',
  'spinning_top': 'Toupie',
  'marubozu': 'Marubozu',
  'tweezer': 'Pince',
  'abandoned_baby': 'Bébé abandonné',
  'three_inside': 'Trois intérieurs',
  'three_outside': 'Trois extérieurs',
  'rising_three': 'Trois ascendants',
  'falling_three': 'Trois descendants',
  'upside_gap': 'Gap haussier',
  'downside_gap': 'Gap baissier',
  'kicking': 'Coup de pied',
  'ladder': 'Échelle',
  'three_line_strike': 'Grève à trois lignes',
  'two_crows': 'Deux corbeaux',
  'unique_three_river': 'Trois rivières uniques',
  'concealing_baby_swallow': 'Hirondelle bébé dissimulée',
  'stick_sandwich': 'Sandwich de bâton',
  'matching_low': 'Bas correspondant',
  'homing_pigeon': 'Pigeon voyageur',
  'ladder_bottom': 'Fond d\'échelle',
  'belt_hold': 'Prise de ceinture',
  'upside_tasuki_gap': 'Gap Tasuki haussier',
  'downside_tasuki_gap': 'Gap Tasuki baissier',
  'side_by_side': 'Côte à côte',
  'separating_lines': 'Lignes de séparation',
  'in_neck': 'Dans le cou',
  'on_neck': 'Sur le cou',
  'thrusting': 'Poussée',
  'mat_hold': 'Maintien du tapis',
  'breakaway': 'Rupture',
  'three_stars_south': 'Trois étoiles du sud',
  'deliberation': 'Délibération',
  'advance_block': 'Bloc d\'avance',
  'stalled_pattern': 'Motif bloqué',
  'doji_star': 'Étoile Doji',
  'dragonfly_doji': 'Doji libellule',
  'gravestone_doji': 'Doji pierre tombale',
  'long_legged_doji': 'Doji à longues jambes',
  'rickshaw_man': 'Homme rickshaw',
  'high_wave': 'Haute vague',
  'counterattack': 'Contre-attaque',
  'meeting_lines': 'Lignes de rencontre',
};