class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'pt': {
      'welcome_back': 'Bem-vindo de volta 👋',
      'sign_in_prompt': 'Por favor, insira seu email e senha para entrar',
      'email': 'Email',
      'password': 'Senha',
      'remember_me': 'Lembrar-me',
      'forgot_password': 'Esqueceu a senha?',
      'dont_have_account': 'Não tem uma conta?',
      'sign_up': 'Cadastre-se',
      'sign_in': 'Entrar',
      'lets_get_started': 'Vamos Começar!',
      'split_bills_easier': 'Com Splitfy, dividir contas é mais fácil do que nunca',
      'continue_with_google': 'Continuar com Google',
      'continue_with_apple': 'Continuar com Apple',
      'continue_with_facebook': 'Continuar com Facebook',
      'continue_with_twitter': 'Continuar com Twitter',
      'log_in': 'Entrar',
      'home': 'Início',
      'settings': 'Configurações',
      'language': 'Idioma',
      'theme': 'Tema',
      'clear_activities': 'Limpar Atividades',
      'logout': 'Sair',
      'dark_theme': 'Tema Escuro',
      'light_theme': 'Tema Claro',
      'system_theme': 'Tema do Sistema',
      'online_users': 'Usuários Online',
      'profile': 'Perfil',
      'notifications': 'Notificações',
      'privacy': 'Privacidade',
      'help': 'Ajuda',
      'about': 'Sobre',
      'enter_phone': 'Digite seu número de telefone',
      'verify_otp': 'Verificar OTP',
      'enter_otp': 'Digite o código OTP',
      'resend_code': 'Reenviar código',
      'verify': 'Verificar',
    },
    'en': {
      'welcome_back': 'Welcome back 👋',
      'sign_in_prompt': 'Please enter your email & password to sign in',
      'email': 'Email',
      'password': 'Password',
      'remember_me': 'Remember me',
      'forgot_password': 'Forgot password?',
      'dont_have_account': "Don't have an account?",
      'sign_up': 'Sign up',
      'sign_in': 'Sign in',
      'lets_get_started': "Let's Get Started!",
      'split_bills_easier': 'With Splitfy, expenses split bills is easier than ever before',
      'continue_with_google': 'Continue with Google',
      'continue_with_apple': 'Continue with Apple',
      'continue_with_facebook': 'Continue with Facebook',
      'continue_with_twitter': 'Continue with Twitter',
      'log_in': 'Log in',
      'home': 'Home',
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'clear_activities': 'Clear Activities',
      'logout': 'Logout',
      'dark_theme': 'Dark Theme',
      'light_theme': 'Light Theme',
      'system_theme': 'System Theme',
      'online_users': 'Online Users',
      'profile': 'Profile',
      'notifications': 'Notifications',
      'privacy': 'Privacy',
      'help': 'Help',
      'about': 'About',
      'enter_phone': 'Enter your phone number',
      'verify_otp': 'Verify OTP',
      'enter_otp': 'Enter OTP code',
      'resend_code': 'Resend code',
      'verify': 'Verify',
    },
    'es': {
      'welcome_back': 'Bienvenido de nuevo 👋',
      'sign_in_prompt': 'Por favor, ingrese su correo y contraseña para iniciar sesión',
      'email': 'Correo',
      'password': 'Contraseña',
      'remember_me': 'Recuérdame',
      'forgot_password': '¿Olvidaste tu contraseña?',
      'dont_have_account': '¿No tienes una cuenta?',
      'sign_up': 'Regístrate',
      'sign_in': 'Iniciar sesión',
      'lets_get_started': '¡Empecemos!',
      'split_bills_easier': 'Con Splitfy, dividir gastos es más fácil que nunca',
      'continue_with_google': 'Continuar con Google',
      'continue_with_apple': 'Continuar con Apple',
      'continue_with_facebook': 'Continuar con Facebook',
      'continue_with_twitter': 'Continuar con Twitter',
      'log_in': 'Iniciar sesión',
      'home': 'Inicio',
      'settings': 'Configuración',
      'language': 'Idioma',
      'theme': 'Tema',
      'clear_activities': 'Limpiar Actividades',
      'logout': 'Cerrar sesión',
      'dark_theme': 'Tema Oscuro',
      'light_theme': 'Tema Claro',
      'system_theme': 'Tema del Sistema',
      'online_users': 'Usuarios en Línea',
      'profile': 'Perfil',
      'notifications': 'Notificaciones',
      'privacy': 'Privacidad',
      'help': 'Ayuda',
      'about': 'Acerca de',
      'enter_phone': 'Ingrese su número de teléfono',
      'verify_otp': 'Verificar OTP',
      'enter_otp': 'Ingrese el código OTP',
      'resend_code': 'Reenviar código',
      'verify': 'Verificar',
    },
    'fr': {
      'welcome_back': 'Bon retour 👋',
      'sign_in_prompt': 'Veuillez entrer votre email et mot de passe pour vous connecter',
      'email': 'Email',
      'password': 'Mot de passe',
      'remember_me': 'Se souvenir de moi',
      'forgot_password': 'Mot de passe oublié?',
      'dont_have_account': "Vous n'avez pas de compte?",
      'sign_up': "S'inscrire",
      'sign_in': 'Se connecter',
      'lets_get_started': 'Commençons!',
      'split_bills_easier': 'Avec Splitfy, diviser les factures est plus facile que jamais',
      'continue_with_google': 'Continuer avec Google',
      'continue_with_apple': 'Continuer avec Apple',
      'continue_with_facebook': 'Continuer avec Facebook',
      'continue_with_twitter': 'Continuer avec Twitter',
      'log_in': 'Se connecter',
      'home': 'Accueil',
      'settings': 'Paramètres',
      'language': 'Langue',
      'theme': 'Thème',
      'clear_activities': 'Effacer les Activités',
      'logout': 'Se déconnecter',
      'dark_theme': 'Thème Sombre',
      'light_theme': 'Thème Clair',
      'system_theme': 'Thème du Système',
      'online_users': 'Utilisateurs en Ligne',
      'profile': 'Profil',
      'notifications': 'Notifications',
      'privacy': 'Confidentialité',
      'help': 'Aide',
      'about': 'À propos',
      'enter_phone': 'Entrez votre numéro de téléphone',
      'verify_otp': 'Vérifier OTP',
      'enter_otp': 'Entrez le code OTP',
      'resend_code': 'Renvoyer le code',
      'verify': 'Vérifier',
    },
    'de': {
      'welcome_back': 'Willkommen zurück 👋',
      'sign_in_prompt': 'Bitte geben Sie Ihre E-Mail und Ihr Passwort ein, um sich anzumelden',
      'email': 'E-Mail',
      'password': 'Passwort',
      'remember_me': 'Erinnere dich an mich',
      'forgot_password': 'Passwort vergessen?',
      'dont_have_account': 'Haben Sie kein Konto?',
      'sign_up': 'Registrieren',
      'sign_in': 'Anmelden',
      'lets_get_started': 'Legen wir los!',
      'split_bills_easier': 'Mit Splitfy ist das Aufteilen von Rechnungen einfacher als je zuvor',
      'continue_with_google': 'Mit Google fortfahren',
      'continue_with_apple': 'Mit Apple fortfahren',
      'continue_with_facebook': 'Mit Facebook fortfahren',
      'continue_with_twitter': 'Mit Twitter fortfahren',
      'log_in': 'Anmelden',
      'home': 'Startseite',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'theme': 'Thema',
      'clear_activities': 'Aktivitäten löschen',
      'logout': 'Abmelden',
      'dark_theme': 'Dunkles Thema',
      'light_theme': 'Helles Thema',
      'system_theme': 'System-Thema',
      'online_users': 'Online-Benutzer',
      'profile': 'Profil',
      'notifications': 'Benachrichtigungen',
      'privacy': 'Datenschutz',
      'help': 'Hilfe',
      'about': 'Über',
      'enter_phone': 'Geben Sie Ihre Telefonnummer ein',
      'verify_otp': 'OTP überprüfen',
      'enter_otp': 'OTP-Code eingeben',
      'resend_code': 'Code erneut senden',
      'verify': 'Überprüfen',
    },
  };

  static String translate(String key, String languageCode) {
    return _localizedValues[languageCode]?[key] ?? 
           _localizedValues['en']?[key] ?? 
           key;
  }

  static List<Map<String, String>> get supportedLanguages => [
    {'code': 'pt', 'name': 'Português'},
    {'code': 'en', 'name': 'English'},
    {'code': 'es', 'name': 'Español'},
    {'code': 'fr', 'name': 'Français'},
    {'code': 'de', 'name': 'Deutsch'},
  ];
}