include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    prefer_const_literals_to_create_immutables: false
    use_key_in_widget_constructors: false
    prefer_typing_uninitialized_variables: false
    prefer_const_constructors_in_immutables: false

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"