workflows:
  android-workflow:
    name: Android Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
      groups:
        - google_play
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $HOME/Library/Caches/CocoaPods
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE | base64 --decode > $CM_BUILD_DIR/keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" <<EOF
          storePassword=$CM_KEYSTORE_PASSWORD
          keyPassword=$CM_KEY_PASSWORD
          keyAlias=$CM_KEY_ALIAS
          storeFile=../keystore.jks
          EOF
      - name: Get Flutter packages
        script: |
          flutter clean
          flutter pub get
      - name: Flutter analyze
        script: |
          flutter analyze --no-fatal-infos --no-fatal-warnings
      - name: Build APK
        script: |
          flutter build apk --release \
            --dart-define=FLUTTER_WEB_AUTO_DETECT=true \
            --target-platform android-arm,android-arm64,android-x64 \
            --split-per-abi
      - name: Build App Bundle
        script: |
          flutter build appbundle --release \
            --dart-define=FLUTTER_WEB_AUTO_DETECT=true
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true