workflows:
  android-release:
    name: Android Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      java: 17
      groups:
        - google_play
      vars:
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
    cache:
      cache_paths:
        - $HOME/.gradle/caches
        - $FLUTTER_ROOT/.pub-cache
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: '*'
          include: true
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > $CM_BUILD_DIR/android/local.properties
      
      - name: Get Flutter packages
        script: |
          cd $CM_BUILD_DIR
          flutter clean
          rm -rf .dart_tool
          rm -rf build
          rm -f pubspec.lock
          flutter pub get
      
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          flutter build apk --release --no-tree-shake-icons
    
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true