name: printerNet
description: 
publish_to: 'none'
version: 1.2.0+5

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #flutter_svg: ^2.0.9
  #animations: ^2.0.11
  #material_symbols_icons: ^4.2785.1
  #ionicons: any
  #xml: ^6.3.0
  #intl: ^0.18.1
  #cached_network_image: ^3.3.0
  #url_launcher: ^6.2.1
  #webview_flutter: ^4.4.2
  #translator: ^0.1.7
  #palette_generator: any
  #ionicons: ^0.2.2
  #google_fonts: ^6.2.1
  #shared_preferences: ^2.2.2
  http: ^1.2.0
  crypto: ^3.0.3
  shared_preferences: ^2.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/config/appconfig.json
    - assets/favicon.png
    - assets/icons/sport_icon_football.png
    - assets/icons/sport_icon_basketball.png
    - assets/icons/sport_icon_tennis.png
    - assets/icons/sport_icon_handball.png
    - assets/icons/sport_icon_volleyball.png
    - assets/icons/sport_icon_hockey.png
    - assets/icons/sport_icon_rugby.png
    - assets/icons/sport_icon_baseball.png
    - assets/icons/sport_icon_boxe.png
    - assets/icons/sport_icon_golf.png
    - assets/icons/sport_icon_cricket.png
    - assets/icons/sport_icon_pingpong.png
    - assets/icons/sport_icon_waterpolo.png
    - assets/icons/sport_icon_badminton.png
    - assets/icons/sport_icon_bike.png
    - assets/icons/sport_icon_moto.png
    - assets/icons/sport_icon_helmet.png
    - assets/icons/sport_icon_footus.png
    - assets/icons/sport_icon_default.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/icon/icon.png
  android: true
  ios: true
  web: true