class LanguageService {
  static Map<String, Map<String, String>> translations = {
    'pt': {
      'home': 'Home',
      'marketplace': 'Marketplace',
      'news': 'Novidades',
      'chat': 'Chat',
      'settings': 'Configurações',
      'logout': 'Sair',
      'profile': 'Perfil',
      'edit_profile': 'Editar Perfil',
      'about': 'Sobre',
      'theme': 'Tema',
      'language': 'Idioma',
      'notifications': 'Notificações',
      'light': 'Claro',
      'dark': 'Escuro',
      'send': 'Enviar',
      'message': 'Mensagem',
      'no_messages': 'Nenhuma mensagem ainda',
      'no_conversations': 'Nenhuma conversa ainda',
      'create_group': 'Criar Grupo',
      'new_conversation': 'Nova Conversa',
      'online': 'Online',
      'offline': 'Offline',
      'tokens': 'Tokens',
      'pro': 'PRO',
      'freemium': 'FREEMIUM',
    },
    'en': {
      'home': 'Home',
      'marketplace': 'Marketplace',
      'news': 'News',
      'chat': 'Chat',
      'settings': 'Settings',
      'logout': 'Logout',
      'profile': 'Profile',
      'edit_profile': 'Edit Profile',
      'about': 'About',
      'theme': 'Theme',
      'language': 'Language',
      'notifications': 'Notifications',
      'light': 'Light',
      'dark': 'Dark',
      'send': 'Send',
      'message': 'Message',
      'no_messages': 'No messages yet',
      'no_conversations': 'No conversations yet',
      'create_group': 'Create Group',
      'new_conversation': 'New Conversation',
      'online': 'Online',
      'offline': 'Offline',
      'tokens': 'Tokens',
      'pro': 'PRO',
      'freemium': 'FREEMIUM',
    },
    'es': {
      'home': 'Inicio',
      'marketplace': 'Mercado',
      'news': 'Noticias',
      'chat': 'Chat',
      'settings': 'Configuración',
      'logout': 'Salir',
      'profile': 'Perfil',
      'edit_profile': 'Editar Perfil',
      'about': 'Acerca',
      'theme': 'Tema',
      'language': 'Idioma',
      'notifications': 'Notificaciones',
      'light': 'Claro',
      'dark': 'Oscuro',
      'send': 'Enviar',
      'message': 'Mensaje',
      'no_messages': 'No hay mensajes aún',
      'no_conversations': 'No hay conversaciones aún',
      'create_group': 'Crear Grupo',
      'new_conversation': 'Nueva Conversación',
      'online': 'En línea',
      'offline': 'Desconectado',
      'tokens': 'Tokens',
      'pro': 'PRO',
      'freemium': 'FREEMIUM',
    },
  };

  static String translate(String key, String locale) {
    return translations[locale]?[key] ?? translations['pt']?[key] ?? key;
  }
}