// language_service.dart
class LanguageService {
  static Map<String, Map<String, String>> translations = {
    'pt': {
      'home': 'Início',
      'marketplace': 'Marketplace',
      'news': 'Novidades',
      'chat': 'Chat',
      'profile': 'Perfil',
      'settings': 'Configurações',
      'logout': 'Sair',
      'login': 'Entrar',
      'signup': 'Criar Conta',
      'email': 'Email',
      'password': 'Senha',
      'name': 'Nome',
      'send': 'Enviar',
      'message': 'Mensagem',
      'online': 'Online',
      'offline': 'Offline',
      'edit': 'Editar',
      'delete': 'Excluir',
      'cancel': 'Cancelar',
      'save': 'Salvar',
      'create_group': 'Criar Grupo',
      'group_name': 'Nome do Grupo',
      'description': 'Descrição',
      'members': 'Membros',
      'admin_panel': 'Painel Admin',
      'theme': 'Tema',
      'language': 'Idioma',
      'light': 'Claro',
      'dark': 'Escuro',
      'tokens': 'Tokens',
      'upgrade_pro': 'Upgrade para PRO',
      'no_messages': 'Nenhuma mensagem ainda',
      'no_chats': 'Nenhuma conversa ainda',
      'no_groups': 'Nenhum grupo ainda',
      'search': 'Pesquisar',
      'help': 'Ajuda',
      'about': 'Sobre',
    },
    'en': {
      'home': 'Home',
      'marketplace': 'Marketplace',
      'news': 'News',
      'chat': 'Chat',
      'profile': 'Profile',
      'settings': 'Settings',
      'logout': 'Logout',
      'login': 'Login',
      'signup': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'name': 'Name',
      'send': 'Send',
      'message': 'Message',
      'online': 'Online',
      'offline': 'Offline',
      'edit': 'Edit',
      'delete': 'Delete',
      'cancel': 'Cancel',
      'save': 'Save',
      'create_group': 'Create Group',
      'group_name': 'Group Name',
      'description': 'Description',
      'members': 'Members',
      'admin_panel': 'Admin Panel',
      'theme': 'Theme',
      'language': 'Language',
      'light': 'Light',
      'dark': 'Dark',
      'tokens': 'Tokens',
      'upgrade_pro': 'Upgrade to PRO',
      'no_messages': 'No messages yet',
      'no_chats': 'No chats yet',
      'no_groups': 'No groups yet',
      'search': 'Search',
      'help': 'Help',
      'about': 'About',
    },
    'es': {
      'home': 'Inicio',
      'marketplace': 'Marketplace',
      'news': 'Noticias',
      'chat': 'Chat',
      'profile': 'Perfil',
      'settings': 'Configuración',
      'logout': 'Salir',
      'login': 'Entrar',
      'signup': 'Crear Cuenta',
      'email': 'Email',
      'password': 'Contraseña',
      'name': 'Nombre',
      'send': 'Enviar',
      'message': 'Mensaje',
      'online': 'En línea',
      'offline': 'Desconectado',
      'edit': 'Editar',
      'delete': 'Eliminar',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'create_group': 'Crear Grupo',
      'group_name': 'Nombre del Grupo',
      'description': 'Descripción',
      'members': 'Miembros',
      'admin_panel': 'Panel Admin',
      'theme': 'Tema',
      'language': 'Idioma',
      'light': 'Claro',
      'dark': 'Oscuro',
      'tokens': 'Tokens',
      'upgrade_pro': 'Actualizar a PRO',
      'no_messages': 'No hay mensajes aún',
      'no_chats': 'No hay conversaciones aún',
      'no_groups': 'No hay grupos aún',
      'search': 'Buscar',
      'help': 'Ayuda',
      'about': 'Acerca de',
    },
  };

  static String translate(String key, String language) {
    return translations[language]?[key] ?? translations['pt']?[key] ?? key;
  }
}
